### ISSUE TITLE
Very dark gamma on all titles when using Remote Play through the Steam Deck gaming mode

### ISSUE THREAD

**Issue by Moonalyn** [ValveSoftware/SteamOS#1246]
System Information
* Steam Deck client version: 1700676668
* PC Steam Version:  1700160213
* Steam API Version:  SteamClient021 (both desktop app and Steam Deck)
* SteamOS version: 3.5.7
* Opted into Steam client beta?: No (I have also tried both on beta and just one side on beta)
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

When using Remote Play on the Steam Deck from my PC (the host) to the handheld (the client), the colors on my PC become very washed out while the colors on the Steam Deck become very very dark, making it nearly impossible to read any text or see any real detail. This is consistent across every game using remote play. 

Using Remote Play in desktop mode functions as expected, the colors are normal on both desktop and the Steam Deck. 

Steps for reproducing this issue:

1. Use Steam Remote Play from Steam deck in gaming mode.

**Comment by kisak-valve** [comment]
Possible duplicate of #1166.

**Comment by bferguson3** [comment]
Bump. 

This issue only occurs when using Hardware Decoding. 
(Unfortunately, without using hardware decoding many games are unplayable due to decoding latency, and the inability to open the Steam Deck menus)

**Comment by gcaragea** [comment]
Bump - same issue, on LCD steam deck. SW decoder works, but higher latency (and no HEVC).

**Comment by safijari** [comment]
Fixed in preview.

**Comment by Foxrida56** [comment]
I can confirm that preview fixed the issue for me in gaming mode.

**Comment by bferguson3** [comment]
The new preview broke streaming completely.

**Comment by Fiorinol** [comment]
Same here. New preview broke remote play. It stays stuck on the Steam loading logo. Worked fine before the last preview update.

This HDR issue makes remote play completely unusable outside of preview on the oled. And now remote play is broken on preview.

**Comment by Foxrida56** [comment]
I’m was on the same preview as I was 2 days ago when I said the fix was good. Without updating to the new preview remote play was suddenly completely broken. I tried updating to the new preview and that didn’t fix the issue. I’m not sure how the issue suddenly began before updating, but as the others have said, todays preview isn’t working.

**Comment by kisak-valve** [comment]
Hello, per "Fixed incorrect colors (gamma) when using Steam In-Home Streaming.` in the [SteamOS 3.5.17](https://steamcommunity.com/games/1675200/announcements/detail/4124805233776242150) update, please update you Steam Deck and retest.

**Comment by break11** [comment]
I tested it in desktop mode and game mode on Steam Deck OLED and Steam Deck LCD and everything works fine, after last update on stable version.

**Comment by durtroSC** [comment]
@kisak-valve  It is not with very dark gamma now but there is gamma changes according to scaling mode and scaling filter that I don't know if they are expected. Both scaling mode Fill and scaling filter Pixel result in higher brightness but they don't stack. Scaling filter Pixel with scaling mode Integer does not have that higher brightness. Summing it:

- Scaling mode fill with any scaling filter is always brighter
- Scaling filter pixel is always brighter except when the scaling mode is integer

**Comment by kisak-valve** [comment]
Hello @durtroSC, please open a new issue report so your feedback can be tracked properly.

**Comment by durtroSC** [comment]
> Hello @durtroSC, please open a new issue report so your feedback can be tracked properly.

Done: https://github.com/ValveSoftware/SteamOS/issues/1405

**Comment by kisak-valve** [comment]
Closing as fixed.
