### ISSUE TITLE
Wi-Fi instability

### ISSUE THREAD

**Issue by michal-grzelak** [ValveSoftware/SteamOS#1256]
I have TP-Link AX50 router and disabled 160Mhz to be able to connect to the network on the Steam Deck. And while I was able to connect to either 2.4Ghz or 5Ghz network with 160Mhz disabled, my connection was really unstable.

What I mean by unstable? I was losing connection every 10-20s for the duration of 20-60s and this cycle would go indefinitely (time random each time). By losing connection I don't mean the device would disconnect from the Wi-Fi network, but that even though the device was connected, it appeared as if connection was frozen during that time.

How it looked like? When downloading a game in Steam, it would download for said 10-20s and then stop downloading for 20-60s, then Steam would resume the download and so on. The game would download eventually, but it's pain. The download speeds were heavily severed too, as reported by other users. In desktop mode the timeouts were longer and working periods shorter. In desktop mode I couldn't download anything as ALL downloads would timeout. When going into "Discover" app, I would get a timeout loading app list. When it somehow loaded I couldn't download any app due to inevitable timeout. I tried to download Firefox and the download timeout all the time (I tried ~30 times).

Things I tried:
- disable 160Mhz in router - it allowed connecting to the network
- reboot SD
- factory reset of SD
- disable Wi-Fi power management in SD dev settings

None of the steps helped with instability. What worked though, I was able to get a stable connection when I created a hotspot on my phone. However, I do not treat it as a fix because I have limited data I can use and besides it's not a fix. But it's worth noting that it worked stable on a hotspot.

Steam Deck information:
- Steam client version: 20231122.1
- SteamOS version: 3.5.7
- Opted into Steam client beta?: No
- Opted into SteamOS beta?: No
- Have you checked for updates in Settings > System?: Yes

It is important to note that ALL my other devices are operating normally and do not have such behavior. They still have access to the internet during the timeout period on Steam Deck.

Also @lostgoat, I would like some sort of confirmation whether it's a software issue you can replicate or it's hardware. If it's hardware then it probably never be fixed, so it won't work with my router probably and I won't bother.

Sample photo of a cycle in Steam (this go on and on as described above):
![IMG_1457](https://github.com/ValveSoftware/SteamOS/assets/29845162/fc2772d7-6e79-4194-b9f5-12dbf294b519)

**Comment by crossedstar** [comment]
I had the same issue with my router at home, an ASUS AX86U Pro (WiFi 6). 

I think it’s an issue with the WiFi driver for Linux- what seemed to work for me was disabling WiFi 6/AX mode from my router (converting it back to a WiFi 5 router / AC mode router), and setting the router to a channel that isn’t in the DFS range or overlaps with one (i tried 36 and 48, both seemed to work). 

After doing the above, the steam deck has been stable on the WiFi. Only sucks that it can’t reliable use wifi 6 just yet 🙃

**Comment by michal-grzelak** [comment]
> I had the same issue with my router at home, an ASUS AX86U Pro (WiFi 6) and my Deck OLED.
> 
> I think it’s an issue with the WiFi driver for Linux- what seemed to work for me was disabling WiFi 6/AX mode from my router (converting it back to a WiFi 5 router / AC mode router), and setting the router to a channel that isn’t in the DFS range or overlaps with one (i tried 36 and 48, both seemed to work).
> 
> After doing the above, the steam deck has been stable on the WiFi. Only sucks that it can’t reliable use wifi 6 just yet 🙃

I think the root cause might be different because it still doesn't work for me. I disabled the AX feature and tested 20/40/80MHz with all non-dfs non-overlapping channels my router supports according to the infographic below and still I had the same exact issue.

![IMG](https://www.tech21century.com/wp-content/uploads/2022/01/best-5ghz-channels.png)

**Comment by crossedstar** [comment]
> > I had the same issue with my router at home, an ASUS AX86U Pro (WiFi 6) and my Deck OLED.
> > I think it’s an issue with the WiFi driver for Linux- what seemed to work for me was disabling WiFi 6/AX mode from my router (converting it back to a WiFi 5 router / AC mode router), and setting the router to a channel that isn’t in the DFS range or overlaps with one (i tried 36 and 48, both seemed to work).
> > After doing the above, the steam deck has been stable on the WiFi. Only sucks that it can’t reliable use wifi 6 just yet 🙃
> 
> It still doesn't work for me. I disabled the AX feature and tested 20/40/80MHz with all non-dfs non-overlapping channels my router supports according to the infographic below and still I had the same exact issue.
> 
> ![IMG](https://camo.githubusercontent.com/2e650193e819379fc369d4133ede907accbb5626bced2f168af9a26d578ac968/68747470733a2f2f7777772e74656368323163656e747572792e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032322f30312f626573742d3567687a2d6368616e6e656c732e706e67)
> 
> --- EDIT --- And this how it looks for me in desktop mode using "Discover" app. Connection is even more unstable and even if app loads, the images won't load and download will timeout as shown. ![IMG_1484](https://private-user-images.githubusercontent.com/29845162/286764986-9fd04c21-ce05-43fc-abe7-4374f3b7791c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMDcyNTMsIm5iZiI6MTcwMTMwNjk1MywicGF0aCI6Ii8yOTg0NTE2Mi8yODY3NjQ5ODYtOWZkMDRjMjEtY2UwNS00M2ZjLWFiZTctNDM3NGYzYjc3OTFjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAxMTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMmNiYjQyYzUzOTZlMjlhYWY5MzQ3NmEzZWU0MjJlOTY2ZjQyMGJlMGY3NThhNjEwMDY3NmI2NWI2ZDU2MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KGfSg71N1EF6l2hKlkKG-ErEhDAWWELsHCbj5tGAWYM)

Dang, sorry to hear that didn’t fix it :/. The only thing I notice with your setup is that the router is an intel-lantiq chipset. Most of the people having issues (like myself) were on a router with a Broadcom chipset.

**Comment by australok** [comment]
> I tried to do that, but I couldn’t get the keyboard working. I know that I should change a setting in BIOS (why is it broken by default?), but honestly I’ve just got a return label and decided I don’t bother anymore.
> 
> Honestly, this device is so much hassle that I will buy it when it’s fixed. Or I will just buy Windows handheld if I can’t wait. I don’t know.
> 
> Nevertheless, I hope the Valve will finally come through and help all users by fixing the Wi-Fi firmware. Thanks @crossedstar for trying to help, the official message from Valve would be appreciated (unless it can’t be fixed by update ;_; - thus silence).

are u polish by the way? because i`m having the exact same problem as u, but with exact, i mean 100% the same issue

**Comment by kagegoomba** [comment]
Seeing this as well except its not targeting any one feature.
Got an AX-6000 TP-Link router.
I've had the steam deck connected on 802.11ax 5Ghz for at least 1 day without issue until it just flat went dead as a post.
Couldn't get it to connect to 2.4Ghz until I turned off WPA3 and went WPA2 instead - that lasted about an hour. With 802.11ax working naturally.

Right now its using "Smart Connect" or what I call AI Managed - where it unifies the bands into one network and just gives the client/device the best connection speed possible.

For the first time since I've owned this Steam Deck (LE OLED 1TB) - its stayed connected throughout the day on numerous wake-from-sleeps without incident. Not yet tested on switching to Wired connection just yet with my Dock then reconnecting back.

Whatever this is - its a driver problem. Something gets stuck/lost in translation.
Every time I've changed the wireless router config - the steam deck just flat refuses to cooperate.
I have to reboot the Steamdeck to even get it to connect - and even then Steam refuses to log in without yet an another reboot.
Then its stable.

It's also using IPv6 in-spite of the fact I've got it fully disabled since I've set my network up years ago.
What I thought was "it hates WPA3 and 802.11ax" - isn't - its like its playing Russian roulette and tends to be in a foul mood more than not.

Currently I'm running 802.11a/b/n at WPA2 (no auto/no 1 no 3) AES-TKIP - had to turn up my Guest Networks as Apples latest iPhone through a hissy fit over the new config (go figure) - which lead me to reboot my Steamdeck twice har har har.

Not sure if this helps or not - but there you go.

Also States - Near Seattle, WA.

**Comment by wright-on** [comment]
I also had this issue with my OLED Deck and connecting to my home network hosted by a ASUS AX86U.

I have separate 2.4GHz and 5GHz home WiFi networks and couldn’t connect to either on my OLED. I had an LCD deck before and could only connect to the 2.4GHz network.

I’ve now changed the following router settings and the connection problems have gone:

Uncheck “Enable 160MHz”
Uncheck “Auto select channel including DFS channels”

![IMG_8844](https://github.com/ValveSoftware/SteamOS/assets/79934653/9c95124b-e12e-43a3-a88f-1112f03433b5)

With the above settings I can connect with no issues.

**Comment by JakeyPrime** [comment]
Can replicate on Meraki MR33's, MR44's, and an Asus AX68U.

**Comment by Crysis85it** [comment]
I tried this setting on a Sagemcom F5684 router.
Disabled the 2.4 wifi network
Set the band to 80 MHz (it's either AUTO which include 160 MHz or you select a specific band.)
Set the channel to 36
Rebooted the router and...no joy

**Comment by Crysis85it** [comment]
I managed to make it connect to my local wifi network by setting the wireless mode to 802.11a+n+ac band width 80MHz and then **factory reset**  the steam deck. Yeah, restarting or rebooting did't work. I had to reset the damn thing (I read this advice here on github or on steam I don't remember)
Anyway this is a lousy workaroung, downgrading the Wi-Fi on my whole house just to run the steam deck it's not great at all. Any word for a possible definitive fix would be appreciated. Thanks

**Comment by octopuserectus** [comment]
I'm having similar Wi-Fi issues with the OLED which are pretty inconsistent.

OS Build: 20231122.1
Steam Version: 1701289036

Router is WS880 with FreshTomato:
Control Channel: 40 - 5.200 GHz
Control Channel Location: LU
Channel Width: 80 MHz

1. Wi-Fi would disconnect some time after switching to desktop. It then reconnects and kinda works.
2. Download speed in Steam would tank similarly to OP for some time, it goes up later but can't reach even 30 MB/s (LCD Deck reached around 40 MB/s consistently in the same conditions and didn't have any issues). Mouse cursor (via Barrier) is noticeably lagging when the speed goes down, then recovers at the same time the speed starts to go up. 

Download speed from Steam is low, but iperf3 results are mostly fine (using in-country servers in both cases):
```
iperf3 -c ser.ver -R -b 0 -t10
Connecting to host ser.ver, port 5201
Reverse mode, remote host ser.ver is sending
[  5] local 192.168.1.20 port 47988 connected to ser.ver port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  40.6 MBytes   340 Mbits/sec                  
[  5]   1.00-2.00   sec  41.4 MBytes   347 Mbits/sec                  
[  5]   2.00-3.00   sec  35.5 MBytes   298 Mbits/sec                  
[  5]   3.00-4.00   sec  46.1 MBytes   387 Mbits/sec                  
[  5]   4.00-5.00   sec  40.8 MBytes   342 Mbits/sec                  
[  5]   5.00-6.00   sec  44.2 MBytes   371 Mbits/sec                  
[  5]   6.00-7.00   sec  43.0 MBytes   361 Mbits/sec                  
[  5]   7.00-8.00   sec  44.2 MBytes   371 Mbits/sec                  
[  5]   8.00-9.00   sec  25.2 MBytes   212 Mbits/sec                  
[  5]   9.00-10.00  sec  42.5 MBytes   357 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.04  sec   423 MBytes   354 Mbits/sec  479             sender
[  5]   0.00-10.00  sec   404 MBytes   339 Mbits/sec                  receiver
```
Testing upload with external hosts is pointless in my case because I have asymmetrical channel. 

LAN tests to a wired host yield strange results as well:
```
iperf3 -c 192.168.1.100 -b 0 -t 10 -R
Connecting to host 192.168.1.100, port 5201
Reverse mode, remote host 192.168.1.100 is sending
[  5] local 192.168.1.20 port 39934 connected to 192.168.1.100 port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  1.50 MBytes  12.6 Mbits/sec                  
[  5]   1.00-2.00   sec  1.12 MBytes  9.44 Mbits/sec                  
[  5]   2.00-3.00   sec  1.62 MBytes  13.6 Mbits/sec                  
[  5]   3.00-4.00   sec  1.88 MBytes  15.7 Mbits/sec                  
[  5]   4.00-5.00   sec   896 KBytes  7.34 Mbits/sec                  
[  5]   5.00-6.00   sec  1.75 MBytes  14.7 Mbits/sec                  
[  5]   6.00-7.00   sec  1.62 MBytes  13.6 Mbits/sec                  
[  5]   7.00-8.00   sec   896 KBytes  7.34 Mbits/sec                  
[  5]   8.00-9.00   sec   384 KBytes  3.15 Mbits/sec                  
[  5]   9.00-10.00  sec  1.88 MBytes  15.7 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.00  sec  13.8 MBytes  11.5 Mbits/sec                  sender
[  5]   0.00-10.00  sec  13.5 MBytes  11.3 Mbits/sec                  receiver


iperf3 -c 192.168.1.100 -b 0 -t 10
Connecting to host 192.168.1.100, port 5201
[  5] local 192.168.1.20 port 50128 connected to 192.168.1.100 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  31.2 MBytes   262 Mbits/sec    0   1.36 MBytes       
[  5]   1.00-2.00   sec  12.5 MBytes   105 Mbits/sec    3   1.01 MBytes       
[  5]   2.00-3.00   sec  28.4 MBytes   238 Mbits/sec    0   1.12 MBytes       
[  5]   3.00-4.00   sec  10.9 MBytes  91.2 Mbits/sec    1   1.12 MBytes       
[  5]   4.00-5.00   sec  24.2 MBytes   203 Mbits/sec    4    895 KBytes       
[  5]   5.00-6.00   sec  27.8 MBytes   233 Mbits/sec    0    980 KBytes       
[  5]   6.00-7.00   sec  22.6 MBytes   190 Mbits/sec    0   1.00 MBytes       
[  5]   7.00-8.00   sec  7.75 MBytes  65.0 Mbits/sec    1   1.23 MBytes       
[  5]   8.00-9.00   sec  29.9 MBytes   251 Mbits/sec    0   1.67 MBytes       
[  5]   9.00-10.00  sec  28.9 MBytes   242 Mbits/sec    0   1.89 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   224 MBytes   188 Mbits/sec    9             sender
[  5]   0.00-10.01  sec   221 MBytes   186 Mbits/sec                  receiver
```

**Comment by dopeytree** [comment]
I also experienced slow wifi on OLED model compared to LCD model. This is also in contrast to my iPhone 15 pro in same spot getting 550Mbps download when OLEd model is getting 3Mbps... 

_However a solution seems to be update to PREVIEW channel OS and it suddenly went up to 550Mbps download on OLED model._

**Have any of you also tried Preview Channel?**

My home network consists of 3x TP-Link TL-WA1201 all hardwired into my pfsense router.

Operating the same network name on both 2.4 & 5Ghz

Every other device works flawlessly.

The slow speed was even when within 2m of the access point.

**Comment by HauieT** [comment]
> I also experienced slow wifi on OLED model compared to LCD model. This is also in contrast to my iPhone 15 pro in same spot getting 550Mbps download when OLEd model is getting 3Mbps...
> 
> _However a solution seems to be update to PREVIEW channel OS and it suddenly went up to 550Mbps download on OLED model._
> 
> **Have any of you also tried Preview Channel?**
> 
> My home network consists of 3x TP-Link TL-WA1201 all hardwired into my pfsense router.
> 
> Operating the same network name on both 2.4 & 5Ghz
> 
> Every other device works flawlessly.
> 
> The slow speed was even when within 2m of the access point.

I have tried preview, its the same there. I only found success if I toggled the wifi. Then wifi is stable again, but its annoying having to do that 😅

**Comment by eldfennec** [comment]
> > Replying to [#1256 (comment)](https://github.com/ValveSoftware/SteamOS/issues/1256#issuecomment-1855970349)
> 
> I have tried preview, its the same there. I only found success if I toggled the wifi. Then wifi is stable again, but its annoying having to do that 😅

I am having the same issue. For me switching the Wi-Fi also solves it momentarily. 
Odd thing is that it's like this already from boot. 

I started out with having the known issue that it couldn't connect to the Steam servers even though it was connected to the Wi-Fi (had this on my LCD too!). Starting developer mode and turning off the Wi-Fi power management solved this. However it's ocasionally very unstable still. Have a TP-link AX1500 router, sitting almost next to it when I play.

**Comment by dopeytree** [comment]
Strange

**Comment by krillme** [comment]
I've been having this problem occur during downloads or local transfers too. The download/transfer rate seems to get capped at 5 mbps (almost exactly) until I turn wifi off and on again, or restart the device. Preview branch didn't resolve the problem.

**Comment by Herro95** [comment]
Same Problem here… i thought that it was my Router and replaced it but it‘s actually a driver problem at my Steam Deck. Sometime i have to toogle off/on Wifi multiple times to get it working. Im using moonlight to stream games on my Deck and when this happens my connection is lagging af…

**Comment by Plagman** [comment]
Can you test on the 3.5.12 Preview build if possible?

**Comment by octopuserectus** [comment]
Thank you for keeping an eye on it, @Plagman. 
Not sure if this is placebo or not, in general the Wi-Fi network seems a bit more stable and "lags" less; however, I have experienced the same Wi-Fi crash on 3.5.12 too. Before it was happening a minute or two after switching to Desktop mode, this time, however, it occurred a bit later. I have not changed any router settings, you can see my configuration in my previous post in this issue. If I can provide a log that would help, I'd be happy to do so.

**Comment by Herro95** [comment]
Tested on 3.5.12 and it’s still happening 😞

**Comment by dopeytree** [comment]
For me this this was fixed with the previous preview build.

Others who are having issues can you try and post more detail about your wifi?

What channel & frequency is the wifi on?

On steamdeck go to desktop mode and click on wifi icon to get more info.

Also do you run the frequencies as the same name (I do). some people use different names for the 5/6ghz frequencies.

Do you use band steering on the wifi AP.

Physically how far are you from the router etc.

:-)

**Comment by Herro95** [comment]
After the update it runs minimally better but every 10-20 minutes the performance goes down and it starts to lag... the Steam Deck is connected to Wifi 6 5Ghz Channel 104 with approx. 800mbit speed. 2.4ghz and 5Ghz are separate from each other. The distance is about 5m from the router 😄 if you switch the WLAN off and on again it runs again without problems. It definitely can't be the connection itself or the distance. Other people on Reddit have the same problem even after the update to 3.5.12, so hopefully Valve will release a fix soon. The Battery of the Deck is also full.

**Comment by dopeytree** [comment]
I imagine fundamentally there is a wifi antenna design problem. I've yet to take the OLED apart to compare to LCD but will take more notice of antenna when I do.

**Comment by Herro95** [comment]
It really looks like a temperature problem of the wifi chip  but i didn‘t test it. Maybe it‘s throttling but that would be weird 🤷‍♂️

**Comment by HauieT** [comment]
Hey, just wanted to share my experience troubleshooting this. 

The method ive tested this out is simply running moonlight stream from my pc to deck.
Like many have reported, i also get this wifi instability after 10-20min of use.

i have finally found a workaround (which is not a solution!) that can help you avoid getting the instability while in the middle of your game.

So I noticed that this instability for me only happens when the deck is restarted from sleep or off, and autoconnect to wifi is on. 

Autoconnect to ssid in game mode is currently busted, so i tested to do forget wifi, restarted the deck, manually connected back to wifi and did moonlight stream. No wifi degradation even after over an hour of gaming!

So I came to the conclusion that somethings is wrong with the autoconnect to wifi on wake up. As I work around, I currently do this when I use it for moonlight stream.

1. Go to desktop mode
2. Go to wifi settings and uncheck autoconnect to wifi (desktop mode autoconnect seems to work still)
3. Sleep and wake to confirm that wifi is not auto connected
4. Manually connect to wifi in desktop mode
5. Go to game mode.
6. Open moonlight stream and stream your game
7. After done with your gaming session, go back to desktop mode and sleep

Do not connect to wifi via gaming mode, as this will turn autoconnect to wifi again.

As I mentioned, this is just a workaround. Let me know if this works for you. If it does, then something is definitely busted with the wifi autoconnect, and hopefully can narrow down the problem for the developers.

**Comment by dopeytree** [comment]
> It really looks like a temperature problem of the wifi chip but i didn‘t test it. Maybe it‘s throttling but that would be weird 🤷‍♂️

Yeah could well be as there was a massive issues with intel's 2.5Gb network chips they went though 4 revisions. 
Does it report temperature of the wifi chip anywhere?

**Comment by HauieT** [comment]
> > It really looks like a temperature problem of the wifi chip but i didn‘t test it. Maybe it‘s throttling but that would be weird 🤷‍♂️
> 
> Yeah could well be as there was a massive issues with intel's 2.5Gb network chips they went though 4 revisions. Does it report temperature of the wifi chip anywhere? Think sensors in terminal might work?

I highly doubt its related to temp tbh. Makes no sense why toggling off/on would suddenly stabilize it.
As I mentioned earlier, I think this issue is related to some type of bug from wifi autoconnect when the device is turned on.

Try out my workaround I mentioned. I can run moonlight no problem when I do it. While when I use autoconnect, wifi would go garbage after 10-20min of streaming.

**Comment by markusressel** [comment]
@HauieT Doesn't work for me. Although the data rate has definitely increased quite a bit since my last tests on this incredibly annoying bug (45MB/s), connecting manually doesn't fix the issue. The transmission is perfectly fine for about a minute at 45MB/s and then suddenly drops to zero, while still seemilgly beeing connected.

I have a 2.4 / 5 GHz split WiFi, using separate SSIDs for each, this is the WiFi information on my Turris Omnia in Luci:

```
Encryption: WPA2 PSK (CCMP)
Channel: 36 (5.180 GHz)
Tx-Power: 23 dBm
Signal: -55 dBm | Noise: -101 dBm
Bitrate: 394.8 Mbit/s | Country: DE
```

Someone at valve really needs to fix this, it makes the device **unusable** if you want to download a current AAA game that is 70GB in size or more. I am a nerd and can find my way around this (f.ex. using a USB LAN adapter), but most gamers will not!! This issue has been present since the launch of the original Deck (which I have) and is somehow still present on the OLED variant?! **Please** investigate this!

**Comment by safijari** [comment]
Tried 3.5.12 and it seemed to make the problem worse for me. For now I'm getting a wifi dongle and in the meantime USB tethering off my phone whenever I use Moonlight.

**Comment by Herro95** [comment]
@HauieT Unfortunately, that didn't change anything for me either. It is also partly random whether it runs for longer or just 10-20 minutes. I'm really considering sending the device back, as Valve hasn't provided a fix since the previous model.

**Comment by eldfennec** [comment]
I tried disabling AX (Wifi 6) and 2.4 ghz and what not on my router. No change, it works for a few minutes (Around 5 at the most), then gets slow unless I switch wifi on and off. For now my best workaround is just keeping it connected to 2.4 ghz. That seems to be somewhat stable for me but clearly slower. 

It works well enough with Moonlight and I plug it into ethernet when downloading something more significant. I shouldn't have to rely on that though.

**Comment by Herro95** [comment]
Can someone test whether it also happens on Windows? It would help to narrow down the error. As far as I know, you can use the Qualcomm wifi driver from Lenovo?

**Comment by late-lattee** [comment]
@Herro95 did you try opening a ticket with Steam support team?? They could look at your device's logs, right?

**Comment by Herro95** [comment]
@late-lattee it‘s like calling the Microsoft support you know 😂

**Comment by Herro95** [comment]
the problem is gone since 3.5.13 but i will test again tomorrow. Just played a while and no lags yet… fingers crossed 😊

**Comment by safijari** [comment]
> the problem is gone since 3.5.13 but i will test again tomorrow. Just played a while and no lags yet… fingers crossed 😊

Not my experience. I had an issue earlier today again on 3.5.13. Anecdotally it took a lot longer for the issue to surface though.

**Comment by HauieT** [comment]
Still getting lags in moonlight after waking up the deck. What’s weird is that when I get the lag, I can open Steam Menu > settings > bluetooth, then quit Steam menu, and the lag will go away.
Does this happen to you guys?

**Comment by Herro95** [comment]
yep still lagging today and when you‘re pressing the Steam button in moonlight the lags are gone wtf. When you push it again to go back in game it‘s lagging…. WHAT

**Comment by absamue** [comment]
Are those with the Moonlight lagging issue using MoonDeck or Moonlight directly? I tested playing Risk of Rain 2 at 1920x1200 50mpbs, OLED 512g model, 5ghz wifi, and observed:

- Launching the game through MoonDeck, the lagging will show up after 10-15 minutes of play. Sleeping the device or opening the steam menu will temporarily fix the issue, but it will return relatively quickly.
- Launching Moonlight directly in game mode, I don't observe any instability issues whatsoever for 30+ minutes of play. 

However I have seen reports of others having the lagging issue when opening Moonlight directly, so I'm not sure if there's much weight to this.

**Comment by HauieT** [comment]
> yep still lagging today and when you‘re pressing the Steam button in moonlight the lags are gone wtf. When you push it again to go back in game it‘s lagging…. WHAT

Yeah, its super weird right? If you go to settings > bluetooth then exit steam menu. The lag will be gone altogether. I have no clue why it does that.

**Comment by blackgold9** [comment]
Is it network lagging or decoding lagging?
I could see the decoder acting up and an overlay triggering something.

**Comment by HauieT** [comment]
> Is it network lagging or decoding lagging? I could see the decoder acting up and an overlay triggering something.
> […](#)

I think it’s network lagging. I could observe from my router that tx rate hits rock bottom from the steam deck whenever this happens. Going to steam menu > bluetooth, makes the tx rate normal again. It’s like the wifi goes into power save mode for some reason.

**Comment by blackgold9** [comment]
Weird. And I assume you turned off the power save in the developer menu?

**Comment by HauieT** [comment]
> Weird. And I assume you turned off the power save in the developer menu?
> […](#)

Tbh, its best to assume that most ppl who dwell in this and #1253 already did that. It’s like the first thing ppl have pointed out, and it does nothing :/

**Comment by hvmzx** [comment]
A lot of us reported this issue, hopefully Valve brings a software fix asap because it's been going for some time now and it affects too many owners of the oled

**Comment by safijari** [comment]
This is still an issue especially coming out of sleep.

**Comment by Herro95** [comment]
Perhaps someone can write a plugin for Decky so that, for example, the WLAN card is addressed every 5 minutes in the background so that this bug does not occur. You can certainly call up the wireless settings with a command line or search for WLAN networks. Maybe that works..

**Comment by Sweetcheezus** [comment]
Still no acknowledgement from Valve regarding this is crazy. This should not be going on for this long with a $600-700 device.

**Comment by safijari** [comment]
> Perhaps someone can write a plugin for Decky so that, for example, the WLAN card is addressed every 5 minutes in the background so that this bug does not occur. You can certainly call up the wireless settings with a command line or search for WLAN networks. Maybe that works..

What does this mean? Is there a workaround that doesn't involve toggling the wifi? Can you give me details.

I write Decky plugins (e.g. Recorder, Reshadeck) I could whip something up pretty quick if that's a solution.

**Comment by Herro95** [comment]
> > Perhaps someone can write a plugin for Decky so that, for example, the WLAN card is addressed every 5 minutes in the background so that this bug does not occur. You can certainly call up the wireless settings with a command line or search for WLAN networks. Maybe that works..
> 
> What does this mean? Is there a workaround that doesn't involve toggling the wifi? Can you give me details.
> 
> I write Decky plugins (e.g. Recorder, Reshadeck) I could whip something up pretty quick if that's a solution.

That would be great :-)
We suspect that moonlight ensures that the wifi card is put into a kind of power saving mode and when you call up the WLAN or Bluetooth settings under Steam OS, it is woken up again. You don't have to actively switch WLAN off and on, that's the crazy thing. Perhaps Steam OS does not correctly recognize that an active application requires full Wifi performance and throttles it down.

**Comment by Black-Seraph** [comment]
@Herro95 @safijari Opening the BT or WiFi settings menu issues a scan command to the card, these are usually detrimental to throughput / latency and somewhat time intensive, but do temporarily disable any and all power-savings and up the TX power for the sake of improving scan results.

If you want to simulate this programmatically just issue a console scan command:
`iw wlan0 scan`

Looking forward to that experimental Decky plugin.

**Comment by AndrewJRichardson** [comment]
Experienced this on two different routers now. Happens on both 5Ghz and 6Ghz.

I don't think its limited to Moonlight. I find it happens even when downloading a game from Steam.

**Comment by deedeeped** [comment]
I’d also love to see if this hypothetical plugin would assist with streaming from Chiaki4Deck. I always have to toggle WiFi on and off to get a solid stream going. Once I do this after the initial disconnection, everything is great, though.

**Comment by tygeezy** [comment]
Just came here to report I have the same exact issues with the degrading wifi performance that dramatically affects streaming with moonlight and even downloading games. Even still the wifi performance is just bad on the deck oled. I can get max 180 mbit out of my deck oled, but I can pull 600 + mbit using iPerf 3 testing with my iPhone.

**Comment by late-lattee** [comment]
> Just came here to report I have the same exact issues with the degrading wifi performance that dramatically affects streaming with moonlight and even downloading games. Even still the wifi performance is just bad on the deck oled. I can get max 180 mbit out of my deck oled, but I can pull 600 + mbit using iPerf 3 testing with my iPhone.

Quick question: did you use iperf3 on deck OLED as well? or did you compare iperf3 results with iPhone to another scenario on deck OLED?

**Comment by tygeezy** [comment]
No, just download speed of games. My iperf3 tests were with my iPhone as the client. I guess I can try and get iPerf 3 working on the deck. The iPhone app is really easy to setup.

**Comment by dontpokethebear3893** [comment]
> Just came here to report I have the same exact issues with the degrading wifi performance that dramatically affects streaming with moonlight and even downloading games. Even still the wifi performance is just bad on the deck oled. I can get max 180 mbit out of my deck oled, but I can pull 600 + mbit using iPerf 3 testing with my iPhone.

Same exact for me. I get gigabyte download speeds from 6e wifi from my other devices. Steam deck OLED only ever has 2/3 wifi bar strength and downloads max out at 150mbps. I have already tried disabling wifi power savings to no avail. I really wish this was fixed.

**Comment by AndrewJRichardson** [comment]
Seeing the same. My downloads and network transfers from Steam cap out at about 320Mbps when on 5ghz or 6ghz, usually settle at around 250Mbps. Tried it with two different routers, same results. Same in both desktop and gaming mode.

Running a speedtest in a browser has it hitting 700-800Mbps. 

Double checked to make sure none of the speed limiting features of Steam are enabled.

**Comment by darrenhaken** [comment]
> > Perhaps someone can write a plugin for Decky so that, for example, the WLAN card is addressed every 5 minutes in the background so that this bug does not occur. You can certainly call up the wireless settings with a command line or search for WLAN networks. Maybe that works..
> 
> What does this mean? Is there a workaround that doesn't involve toggling the wifi? Can you give me details.
> 
> I write Decky plugins (e.g. Recorder, Reshadeck) I could whip something up pretty quick if that's a solution.

Are you working on a Decky plugin, then?

**Comment by safijari** [comment]
> > > Perhaps someone can write a plugin for Decky so that, for example, the WLAN card is addressed every 5 minutes in the background so that this bug does not occur. You can certainly call up the wireless settings with a command line or search for WLAN networks. Maybe that works..
> > 
> > 
> > What does this mean? Is there a workaround that doesn't involve toggling the wifi? Can you give me details.
> > I write Decky plugins (e.g. Recorder, Reshadeck) I could whip something up pretty quick if that's a solution.
> 
> Are you working on a Decky plugin, then?

No. The operation specified (scan) tanks the wifi performance for a good 10 seconds so it's not useful to have it be running constantly. It also did not fix the issue for me the few times I've tried it.

**Comment by nick-delirium** [comment]
Welp, got the issue as well

OLED deck is refusing to connect to 5Ghz network while working fine with 2.4ghz, I noticed that it happens after you download ~10-20gb of anything over 5ghz. Restarting the router helps until you start downloading anything big. 

For comparison, I have LCD model in my family as well and it never happens for it (well, to be honest it happened ONCE 3+ years ago, but it's a preorder model from first batches and I never faced that issue again)

**Comment by late-lattee** [comment]
> Welp, got the issue as well
> 
> OLED deck (stable latest) is refusing to connect to 5Ghz network while working fine with 2.4ghz, I noticed that it happens after you download ~10-20gb of anything over 5ghz. Restarting the router helps until you start downloading anything big.
> 
> For comparison, I have LCD model (stable latest as well) in my family as well and it never happens for it (well, to be honest it happened ONCE 3+ years ago, but it's a preorder model from first batches and I never faced that issue again)

Oh, what router are you using? You may want to file a support ticket with them...

**Comment by Black-Seraph** [comment]
Try this:

sudo mv /etc/NetworkManager/conf.d/wifi_backend.conf /etc/NetworkManager/conf.d/wifi_backend.conf.bak

Then reboot and report back.

**Comment by ScraggyMcRaggy** [comment]
> Try this:
> 
> 
> 
> sudo mv /etc/NetworkManager/conf.d/wifi_backend.conf /etc/NetworkManager/conf.d/wifi_backend.conf.bak
> 
> 
> 
> Then reboot and report back.

No changes from what I can tell. How would I revert back?

**Comment by Black-Seraph** [comment]
Try this:

sudo mv /etc/NetworkManager/conf.d/wifi_backend.conf /etc/NetworkManager/conf.d/wifi_backend.conf.bak

Then reboot and report back.

> > Try this:
> > sudo mv /etc/NetworkManager/conf.d/wifi_backend.conf /etc/NetworkManager/conf.d/wifi_backend.conf.bak
> > Then reboot and report back.
> 
> No changes from what I can tell. How would I revert back?

By renaming the file back to it's original file name.

Just shave off the .bak extension.

sudo mv /etc/NetworkManager/conf.d/wifi_backend.conf.bak /etc/NetworkManager/conf.d/wifi_backend.conf

**Comment by SproedKartoffelChip** [comment]
Throwing a fix out there for my LCD Deck that's had wifi instability since I got it back in August 2022.

I've got a set of Airties4920 wifi 5 mesh extenders, turning OFF "Wifi steering" immediately halted the repeated disconnecting and reconnecting in desktop mode and I've had zero wifi issues in game mode nor desktop mode ever since. 
I want to note that even connecting to my Galaxy S21 Ultra's 2.4/5 ghz hotspot and creating a secondary SSID on the extender exclusively serving 5 ghz both yielded instability.  

The only other solution I had up until now was creating an SSID on the extender serving 2.4 ghz only.

It's especially odd because this was happening while I was sitting in the same room as the extender just 1-2 meters away from it, so there really shouldn't be any need for it to switch to the extender in the other room.

**Comment by zacbre** [comment]
Can confirm this is still happening on the preview branch as of 4/4/2024. I powered on my steam deck from standby, and I tried to download a game from the heroic client and was met with ~1MB/s speeds. The second I enabled airplane mode and disabled airplane mode, my download started hitting 65MB/s+. This happens in both desktop and game mode. The same kind of thing happens when streaming games via moonlight. It will stutter after a few minutes really badly if woken from standby. The second that I enable/disable airplane mode or reboot, it works great until the next standby.

**Comment by jonginator** [comment]
This bug shows itself on every single streaming I’ve tested (chiaki4deck, xcloud, GeForce now, moonlight/sunshine). 

The easiest way around it is as soon as the stutter occurs, hit the menu button and scroll through the menu past WiFi and Bluetooth. 

This seems to re-awaken the WiFi chip from low power settings. 

Then exit the menu and the stutter will go away.

I hope Valve fixes this. Have they acknowledged an issue?

**Comment by savdagod** [comment]
I am also having the same issue as the two posters above me. Turning WiFi on/off fixes it for as long as I will be streaming (does this using Moonlight and previously Steam In-Home Streaming). It’s definitely annoying to have to do every time and the stutter can really throw you off if you’re mid boss fight or something. Hopefully there’s a fix on the way.

**Comment by appledoc1** [comment]
Yeah also happens for me consistently on my OLED deck, after waking up the deck and using Moonlight for 10 minutes.
Navigating to the wifi menu solution does seem to resolve it.

**Comment by peterwilli** [comment]
I just got my steamdeck oled 1tb and it has similar wifi issues. I thought it was my router so I reset it, I'm literally 2 meters away from the next access point and any device has no problems pulling 50mb/s except the steam deck which sits at 2mb/s if I'm lucky. I'm still investigating.

**Comment by Skillossus** [comment]
Just commenting to say that I have the exact same issue with two unifi 802.11ac access points and a 1tb steam deck OLED.

Toggling then WiFi seems to resolve it and it's reproducible nearly 100% of the time when waking from sleep.

This is the fifth most commented on issue in their issue tracker. Perhaps I missed it but I don't see any response from Valve here? What gives?

**Comment by asktree** [comment]
I'm also getting this issue, OLED. Previously had full internet speeds (100Mbps ?), now 370kbps as measured by fast.com. Restarting router put me up to 1Mbps. All other devices in home get 100Mbps.

**Comment by AlchemicSoul** [comment]
I get this problem daily on the OLED. I have tried everything humanly conceivable including different PC, different Deck, different router/network, etc.

The only way to reliably even temporarily fix this is to reboot the wifi module on the Deck. I tried every home networking trick possible from channel fudgery to SQM, etc. 

On the plus side, I learned a TON about home networking but yeah, no fix other than the toggle.

**Comment by itpropro** [comment]
I have many devices in my network relying on 2.4 Ghz, so disabling is not an option. Please provide a fix for this Valve...

**Comment by absamue** [comment]
I want to highlight this comment from a different issue: [Deck OLED on wifi6 routers goes into low power mode when streaming](https://github.com/ValveSoftware/SteamOS/issues/1445#issuecomment-2108254949)

After creating the conf file and restarting I have been able to stream over wifi in moonlight without any stuttering issues, including after wake from sleep. Even increasing the bitrate higher than I attempted to before is a stable experience.

Using Stable updates channel, wifi 5 5ghz.

**Comment by HauieT** [comment]
> I want to highlight this comment from a different issue: [Deck OLED on wifi6 routers goes into low power mode when streaming](https://github.com/ValveSoftware/SteamOS/issues/1445#issuecomment-2108254949)
> 
> After creating the conf file and restarting I have been able to stream over wifi in moonlight without any stuttering issues, including after wake from sleep. Even increasing the bitrate higher than I attempted to before is a stable experience.
> 
> Using Stable updates channel, wifi 5 5ghz.

Didn’t work for me unfortunately

**Comment by absamue** [comment]
> > I want to highlight this comment from a different issue: [Deck OLED on wifi6 routers goes into low power mode when streaming](https://github.com/ValveSoftware/SteamOS/issues/1445#issuecomment-2108254949)
> > After creating the conf file and restarting I have been able to stream over wifi in moonlight without any stuttering issues, including after wake from sleep. Even increasing the bitrate higher than I attempted to before is a stable experience.
> > Using Stable updates channel, wifi 5 5ghz.
> 
> Didn’t work for me unfortunately

Did you restart the deck after creating the file? This will not have any effect until NetworkManager is restarted to pick up the change.

**Comment by HauieT** [comment]
> > > I want to highlight this comment from a different issue: [Deck OLED on wifi6 routers goes into low power mode when streaming](https://github.com/ValveSoftware/SteamOS/issues/1445#issuecomment-2108254949)
> > > After creating the conf file and restarting I have been able to stream over wifi in moonlight without any stuttering issues, including after wake from sleep. Even increasing the bitrate higher than I attempted to before is a stable experience.
> > > Using Stable updates channel, wifi 5 5ghz.
> > 
> > 
> > Didn’t work for me unfortunately
> 
> Did you restart the deck after creating the file? This will not have any effect until NetworkManager is restarted to pick up the change.

Yup, restarted both with sudo systemctl restart NetworkManager and restarting the deck itself. But didn’t help. May I ask what your network setup is. Router or AP model? When you run iwconfig wlan0 in konsole, does it say on or off in Power management?

**Comment by absamue** [comment]
> > Replying to [#1256 (comment)](https://github.com/ValveSoftware/SteamOS/issues/1256#issuecomment-2186637765)
> 
> Yup, restarted both with sudo systemctl restart NetworkManager and restarting the deck itself. But didn’t help. May I ask what your network setup is. Router or AP model? When you run iwconfig wlan0 in konsole, does it say on or off in Power management?

A single [Google Wifi Point](https://support.google.com/googlenest/answer/6300732?hl=en) (no mesh setup). 

And power management is off:
`(deck@steamdeck ~)$ iwconfig wlan0
wlan0     IEEE 802.11  ESSID:""
          Mode:Managed  Frequency:5.745 GHz  Access Point: 28:BD:89:1F:BE:01
          Bit Rate=866.7 Mb/s   Tx-Power=16 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=70/70  Signal level=-36 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:49   Missed beacon:0`

**Comment by HauieT** [comment]
Has there been any progress at all with the remote play degrading after 10-20 min of use and requires a wifi toggle to make it stable? It’s dead silent here, and valve haven’t adressed this issue. Did valve just give up?

**Comment by typhoe** [comment]
> Has there been any progress at all with the remote play degrading after 10-20 min of use and requires a wifi toggle to make it stable? It’s dead silent here, and valve haven’t adressed this issue. Did valve just give up?

When you say remote play, do you speak about the steam one or the "playstation" remote play ?

I'm encountering the same problem (and use the same solution it seems).

After a various time, my connexion seems to die when I use remote play to play from my steamdeck on my playstations (same problem on either my old ps4 pro or my ps5). I tried with Chiaki-Ng (had the pb with chiaki4deck also before the renaming) and with PSPlay (from StreamingDV), the problem appear with both.

I'm also using OpenWRT (latest) on a Netgear R7800 (AC, tried various channels, various "width" from 20 to 80, enabling/disabling Wi-Fi Multimedia (WMM) Mode QoS).

Every time my remote play session get stuck, toggling the wifi on/off is enough to recover (I'm not even disconnected from my remote play session).

What kind of logs / debug session would help to solve or at least identify the exact problem ?

**Comment by krillme** [comment]
"Remote play" just means running a game on one device and streaming it to the Steam Deck. Could be from a PlayStation, a PC, or some other setup, it's all the same technology, all suffer the same problem.

I have a dedicated game streaming router that the only devices that are connected to it are the host PC and the streaming device (either a Steam Deck or Oculus Quest, never both at the same time). I had great success with this setup on my LCD Steam Deck, but the OLED suffers from this dreaded issue. Others have documented it much better than I have, but the gist is after a few minutes of playing network jitter abruptly skyrockets, causing the stream to either freeze for several seconds at a time, increase latency by multiple seconds, or disconnect entirely.

I personally have never had success with "scrolling past wifi" regardless if it's in the QAM or the Settings page, I always have to toggle it on and off. Lately even that hasn't solved the issue and I usually have to restart the Steam Deck entirely.

**Comment by safijari** [comment]
I have had good luck with this issue while using the wifi debug mode. If you're on 3.6 (beta or preview at the moment) you can go to Developer settings (of course enable developer mode from System) and toggle on "Enable WiFi debug data collection". You can confirm this is working by doing
```
(deck@steamdeck ~)$ /usr/lib/steamos-get-wifidebug
u 1
```
I've had this enabled for a few months now and cannot remember the last time I had an issue. Definitely more of a band-aid but hey I'm not complaining.

**Comment by carpeggios** [comment]
> Toggling the WiFi seems to resolve it and it's reproducible nearly 100% of the time when waking from sleep.

> toggle on "Enable WiFi debug data collection". 

Does this prevent Wifi from sleeping then? If so, that could be more evidence that sleep/waking is the cause of the issue.

**Comment by DriftingShadows** [comment]
> I have had good luck with this issue while using the wifi debug mode. If you're on 3.6 (beta or preview at the moment) you can

do you konw what that setting actually does? From the name it sounds like its just collecting debug data as opposed to actually changing the way wifi behaves.

**Comment by rob151515** [comment]
> I have had good luck with this issue while using the wifi debug mode. If you're on 3.6 (beta or preview at the moment) you can go to Developer settings (of course enable developer mode from System) and toggle on "Enable WiFi debug data collection". You can confirm this is working by doing
> 
> ```
> (deck@steamdeck ~)$ /usr/lib/steamos-get-wifidebug
> u 1
> ```
> 
> I've had this enabled for a few months now and cannot remember the last time I had an issue. Definitely more of a band-aid but hey I'm not complaining.

Tried this and didn't do anything for me... Wifi still falls apart 5 minutes after starting a Moonlight stream.

**Comment by deedeeped** [comment]
I agree. I’ve configured everything possible in my network to avoid the streaming interruptions, including everything mentioned on this thread (beta branch, WiFi debug, force wpa_supplicant, use an IP reservation, etc.). Nothing works, unfortunately. Until the WiFi chip’s drivers are updated to forego this low power/passive mode while streaming, we will always have to toggle WiFi on and off to get the stream going again. It’s a bummer.

**Comment by hvmzx** [comment]
At least it looks like it's a software issue, hoping it gets resilved soon  given it's affecting a lot of people

**Comment by cardonator** [comment]
I just got my OLED back from a repair and it is doing this constantly now. Ever since I turned it on, it had issues logging me in, had issues downloading games again, I went into Desktop mode and ran a ping and it loses packets constantly. On a ping, it can barely get through 15 frames before it's losing packets. I tried to switch to the Beta channel and no dice.

**Comment by jonginator** [comment]
Has Valve even acknowledged this issue?

**Comment by Black-Seraph** [comment]
@jonginator No. They still pretend this doesn't exist.

I've had countless fights with Valve's customer support over this.

**Comment by hvmzx** [comment]
If it was possible to send the steamdeck back because of this, i would, because it's really bothering me

**Comment by deedeeped** [comment]
Hey @kisak-valve, you might look into this comment on Reddit, as it seems to have alleviated the streaming degradation that I and many others have noticed. I found this solution on  Reddit:

“I've been having stream stuttering issues despite trying all these fixes for months and I think I've finally found a solution. I'm still testing this but I've been having a solid 20 minutes of stutter-free streaming with Moonlight with the following tweak:

•	⁠Disable background scan in iwd or wpa_supplicant, depending on what you use.

For wpa_supplicant, you want to put bgscan="" and update_config=0 (to prevent NetworkManager from re-inserting runtime scan values) somewhere near the top of /etc/wpa_supplicant/wpa_supplicant.conf:

update_config=0
bgscan=""

For iwd you want to add this to /etc/iwd/main.conf:

[Scan]
DisablePeriodicScan=true

I've only tested it in wpa_supplicant but this should achieve the same result with this iwd config

Update 4 days later: sticking update_config=0 in wpa_supplicant.conf seems to solve the NetworkManager issue and can thus be left enabled for full wifi management.”

I’ve been able to maintain a consistent stream with iwd for the past couple of days even when waking from sleep on the OLED, similarly to what I was able to do on my LCD deck. Perhaps it can be added as an update in the future?

**Comment by octopuserectus** [comment]
While I don't have iwd/main.conf nor wpa_supplicant.conf, I have tried adding something similar to /etc/NetworkManager/NetworkManager.conf:
```[device]
wifi.scan-rand-mac-address=no

[wifi]
bgscan="none"
```
While testing with `mcli device wifi list` I noticed that I get the same mouse lag (I'm using Barrier on another computer to control the Deck) right after running the command, similar to the Wi-Fi issues I have with OLED (however, it doesn't disconnect, when it happens by itself the network connection dies), so it might be indeed related to the background scanning.

**Comment by deedeeped** [comment]
I had to add those config files as they weren’t there for me, either, but they seem to have alleviated the issue.

**Comment by Mothamoz** [comment]
> Hey @kisak-valve, you might look into this comment on Reddit, as it seems to have alleviated the streaming degradation that I and many others have noticed. I found this solution on Reddit:
> 
> “I've been having stream stuttering issues despite trying all these fixes for months and I think I've finally found a solution. I'm still testing this but I've been having a solid 20 minutes of stutter-free streaming with Moonlight with the following tweak:
> 
> • ⁠Disable background scan in iwd or wpa_supplicant, depending on what you use.
> 
> For wpa_supplicant, you want to put bgscan="" and update_config=0 (to prevent NetworkManager from re-inserting runtime scan values) somewhere near the top of /etc/wpa_supplicant/wpa_supplicant.conf:
> 
> update_config=0 bgscan=""
> 
> For iwd you want to add this to /etc/iwd/main.conf:
> 
> [Scan] DisablePeriodicScan=true
> 
> I've only tested it in wpa_supplicant but this should achieve the same result with this iwd config
> 
> Update 4 days later: sticking update_config=0 in wpa_supplicant.conf seems to solve the NetworkManager issue and can thus be left enabled for full wifi management.”
> 
> I’ve been able to maintain a consistent stream with iwd for the past couple of days even when waking from sleep on the OLED, similarly to what I was able to do on my LCD deck. Perhaps it can be added as an update in the future?

Can confirm that the above fixed my longstanding wifi issues, moonlight runs like a dream now!

**Comment by deedeeped** [comment]
I’m back to say that you’re right; remote play on 5Ghz channels with the OLED is simply not ever consistent, unfortunately. I don’t know whether this will ever be fixed.

**Comment by deedeeped** [comment]
I’m back again, this time with another solution. I’ve tested it from wake per the user’s instructions I’ve linked here, and I take no credit for it. This far, it actually, really seems to work, so give it a shot: https://github.com/ValveSoftware/SteamOS/issues/1445#issuecomment-2492741774
This one restarts network manager upon waking the deck from suspend-mode. Try it and see if that works for you.

**Comment by outerwinnie** [comment]
Hey! I had the same issue, but i just found this today: https://github.com/felipejfc/decky-wifi-locker

I tried for like an 1h playing AC:Shadows and it seems to work! It's not on the store yet, but you can install it manually. I hope Valve can take a look at it, and fix it without needing a plugin.

**Comment by rob151515** [comment]
> Hey! I had the same issue, but i just found this today: https://github.com/felipejfc/decky-wifi-locker
> 
> I tried for like an 1h playing AC:Shadows and it seems to work! It's not on the store yet, but you can install it manually. I hope Valve can take a look at it, and fix it without needing a plugin.

Interesting. Have you left your Deck to sleep overnight yet? I’ve seen a lot of potential workarounds posted for this issue but none of them work after a prolonged sleep. I’m thinking booting into desktop mode then back into gaming mode “fixes” the problem until the next prolonged sleep session.

**Comment by gordmit** [comment]
Had all same problems with wifi on SD OLED 1TB - restartings, switching between 2.4ggz and 5ghz, switching channels and parameters on wifi router.

...emm and i switched off Bluetooth on SD and wifi works perfectly (5ghz wifi6). 

Still checking how its works after sleep/hibernation, but seems bluetooth is messing with wifi connection

**Comment by Sunspark-007** [comment]
If wifi works perfectly when bluetooth is switched off, then the issue may be bluetooth coexistence. I remember there was a switch for it in my old broadcom router. If it wasn't toggled on, the PS3 bluetooth controller wasn't happy when the wifi was running at the same time. With it on, it was fine.

Not saying this is the issue, but if your router has that chip, look for the coexistence setting inside it somewhere.
