### ISSUE TITLE
Performance Degradation in Forza Horizon 4 with Allow Tearing+ Crashes

### ISSUE THREAD

**Issue by ffrasisti** [ValveSoftware/SteamOS#1300]
#### Your system information

* SteamOS version: 3.5.7
* Opted into Steam client beta?: [No] 
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.
Forza Horizon 4, on using 3.5.7, despite using the same version of proton and sd card as my 3.4.1 deck, in contrast to 3.4.1:
-Does not play the intro videos, only sound
- Has slightly worse framepacing, at least when framerate cap is in place
- On the overworld, the game drops frames below my 40 cap more frequently on the same settings, time of day and driving course. and allow tearing on seems to make framerate and framepacing worse.
- The game is more crash-prone on menus. It has a not insignificant chance of crashing on doing anything in the main menu, whereas this only ever happened to me once on 3.4.1
- 
On testing the benchmark, however, i see almost no difference and some of the averages are higher on 3.5.7 
I really wanted to record a few runs in the overworlds but i have no tripod and doing this one handed is a pain

Benchmark:
3.4.1
https://media.discordapp.net/attachments/1059777113303036004/1178917731500822558/3.4.1.jpg?ex=65811e32&is=656ea932&hm=d9a486ee1a71f6169dafaba067f8631a3a1081f7ab83ccef6d47c2f08644c8d1&=&format=webp&width=1332&height=832

3.5.7
https://media.discordapp.net/attachments/1059777113303036004/1178918065853972541/descarga_17.jpg?ex=65811e82&is=656ea982&hm=86c90d554732b6cfdc71d0e7ee8f82343e6577a324c9a0e215f29cdfd9997a29&=&format=webp&width=1332&height=832

My settings:
800p
no ingame vsync
https://drive.google.com/file/d/1XkOx1zcfsXZytHRMRdAMX7IlEq7-zVE4/view?usp=sharing
https://drive.google.com/file/d/1XjVmWwCdZEAdp8a6Ea2AiXScWppJ75Uq/view?usp=sharing

#### Steps for reproducing this issue:

1. Play forza horizon 4 on 3.5.7 on my settings
2. Cap the framerate at 40 
3. Enable allow tearing 
4. Drive around and compare to 3.4.1 in the same settings/route. I would also compare against 3.5.7 same settings and no allow tearing, it drops less frames

**Comment by ffrasisti** [comment]
On my brand new oled the game opens to a menu with a black background and refuses to respond to any commands. I can log into xboxb but no matter if i use proton 8.4 or experimental, the menu is responsless and the background is black

**Comment by waspennator** [comment]
> On my brand new oled the game opens to a menu with a black background and refuses to respond to any commands. I can log into xboxb but no matter if i use proton 8.4 or experimental, the menu is responsless and the background is black

Apparently latest steamos preview update has a note about it.

"Fixed black screen when launching Forza Horizon 4 and other titles on Steam Deck OLED"

**Comment by waspennator** [comment]
https://steamcommunity.com/app/1675200/discussions/0/7529517132617601916/?ctp=33#c4300445879343197156

Forza 4 performance is apparently still not back to how it was with 3.4 and it seems like people are still getting upset about it.

**Comment by ffrasisti** [comment]
It still going? :(El 2 mar. 2024 21:58, waspennator ***@***.***> escribió:
https://steamcommunity.com/app/1675200/discussions/0/7529517132617601916/?ctp=33#c4300445879343197156
Forza 4 performance is apparently still not back to how it was with 3.4 and it seems like people are still getting upset about it.
