### ISSUE TITLE
Dualshock 3 doesn't pair in 3.6.20

### ISSUE THREAD

**Issue by kindkains** [ValveSoftware/SteamOS#1710]
#### Your system information

* Steam client version:
1730853027
* SteamOS version: 
3.6.20
* Opted into Steam client beta?: [Yes/No]
No
* Opted into SteamOS beta?: [Yes/No] 
No
* Have you checked for updates in Settings > System?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

I always was able to connect my original PS3 Controller to the Steam Deck.

1. Plug in via usb
2. Unplug
3. Press PS Button
4. Ready

But since the last Update it seems Impossible

1. Plug in via usb
2. Plugin via usb
3. Unplug
4. Press PS Button
5. Lights are flashing, but nothing happens

I tried to go to desktop mode, opened a terminal and wrote

bluetoothctl devices

But the PS3 Controllers are not listet.

bluetoothctl list

I see only the steamdeck default Controller.

How can I fix this?

![20241106_201250](https://github.com/user-attachments/assets/8b2b3a50-c758-4fdb-87a2-baabb76eb357)

![20241106_201402](https://github.com/user-attachments/assets/a505aab5-74ce-43de-9666-eee0e729c209)

![20241106_201409](https://github.com/user-attachments/assets/87612376-e110-4453-9c4d-1d3bbb54eaed)

**Comment by Sunspark-007** [comment]
I confirm this. I have a Dualshock 3 and it pairs fine with 3.4 but not with 3.6.20.

Add new Bluetooth device in desktop mode doesn't do anything anymore.

**Comment by Sunspark-007** [comment]
I saw this comment on Reddit, haven't tested, but makes sense since the issues I linked talk about bluez:

"After putting the input.conf in place (/etc/bluetooth) just like you did, try this:

You'll need to install bluez-plugins (sudo pacman -S bluez-plugins).
In case pacman whines about pgp signature or something you disable that to install anyways. Remember to re-enable the signature check afterwards.
Next, run the command "bluetoothctl devices Trusted" to list all deviced and "bluetoothctl remove xx:xx:xx:xx:xx:xx" and remove the ps3 controller manually in case it is in there.

Restart your deck. Now you can plug the ps3 controller via usb and wait for the little pop-up asking to trust the device."

/etc/bluetooth/input.conf file should contain these 3 lines:
```
[General]
ClassicBondedOnly=false
UserspaceHID=false

```

Valve really needs to address this.. users should not be expected to create an input.conf file and install a bluez plugin from the terminal.. it should "just work" ideally from the gaming mode without having to drop down to desktop mode like we are discussing here.

**Comment by gytdoo** [comment]
Dropping in to say I’m also experiencing this issue exactly as described in the first post with two different model authentic Sony DualShock 3s. They were previously working fine wirelessly before the 3.6 update. I also noticed in the steam input menu there’s no gyro option when plugged in via usb. Not sure if that’s how it’s always been, but motion controls still function in rpcs3.

Slight side tangent, but it would be very cool if in the process of fixing this, someone found a way to get pressure sensitive buttons to officially be supported in steam input. It’s a very handy feature and these controllers still have many years left in them thanks to their high quality analog sticks.

**Comment by Hahasamian** [comment]
> Valve really needs to address this.. users should not be expected to create an input.conf file and install a bluez plugin from the terminal.. it should "just work" ideally from the gaming mode without having to drop down to desktop mode like we are discussing here.

Dude I've been looking all over for some fix to this issue and then I see this

This is it. This is all I needed to do, create an input.conf file and things are back to how they used to be. Thank you <3

# This right here is the issue: input.conf is missing from /etc/bluetooth ! Please fix it soon 🙏

**Comment by qmgsqyf** [comment]
Same issues here, Valve team please fix it soon. DS3 is my favorite controller.

**Comment by zanito** [comment]
I was having the exact same issue, pairing of ps3 controller worked fine on my linux laptop but it wasn't working on steam deck. What did it for me was probably a combination of input.conf and bluez-plugins install, only the input.conf wasn't working, but after installing bluez-plugins and restarting bluetooth service I finally got the paring request when connecting via USB. So this must indeed be a regression on valve side, I guess this package really needs to be there for ps3 controller to be supported

**Comment by qmgsqyf** [comment]
DS3 is my favorite controller, I have to downgrade steamOS to 3.5.19 to fit my DS3… smh

**Comment by mh-muc** [comment]
i added bluez-plugins and added /etc/bluetooth/input.conf 
But my DS3 controllers do only pair wireless in desktop mode. As soon as i switch to gaming mode the controllers disconnect and do not reconnect wireless again, even after plug in by USB first.
Any way to get it to work in gaming mode? My kids should not start desktop mode...

**Comment by Managor** [comment]
Voicing my interest in adding `ClassicBondedOnly=false` into the Steam Deck configuration files officially.

**Comment by sweetol** [comment]
same issue here. please fix it <3

**Comment by alpepi** [comment]
> I saw this comment on Reddit, haven't tested, but makes sense since the issues I linked talk about bluez:
> 
> "After putting the input.conf in place (/etc/bluetooth) just like you did, try this:
> 
> You'll need to install bluez-plugins (sudo pacman -S bluez-plugins). In case pacman whines about pgp signature or something you disable that to install anyways. Remember to re-enable the signature check afterwards. Next, run the command "bluetoothctl devices Trusted" to list all deviced and "bluetoothctl remove xx:xx:xx:xx:xx:xx" and remove the ps3 controller manually in case it is in there.
> 
> Restart your deck. Now you can plug the ps3 controller via usb and wait for the little pop-up asking to trust the device."
> 
> /etc/bluetooth/input.conf file should contain these 3 lines:
> 
> ```
> [General]
> ClassicBondedOnly=false
> UserspaceHID=false
> ```

@Sunspark-007 This worked for me, thanks! Although I ran into a few extra steps along the way:

1. I couldn't install bluez plugins at first. I had an error that affected folders were read only. I first had to run `sudo steamos-readonly disable` (I re-enabled after installation using `sudo steamos-readonly enable`).
2. To disable signature check, I opened `/etc/pacman.conf`, and changed `SigLevel = Required DatabaseOptional` to `SigLevel = Never` (Similarly, I re-enabled it later).
3. Then, the install failed because of missing keys/keyring. I had to run `sudo pacman-key --init`, then `sudo pacman-key --populate archlinux`.
4. At this point, `sudo pacman -S bluez-plugins)` worked and my PS3 controllers are connecting to bluetooth.

**Comment by Sunspark-007** [comment]
Hi @bertogg, could I ask you to please comment here if you don't mind? bluez-plugins used to be present in SteamOS and now it's not. Will this regression be reviewed? Thanks!

**Comment by Nj0be** [comment]
I can confirm the fix provided by @Sunspark-007 works. I hope Valve will addresses this issue soon. Thanks

**Comment by fledermaus** [comment]
bluez-plugins has been replaced (upstream, in bluez) by bluez-utils.

**Comment by fledermaus** [comment]
This is not to say there's not been a regression, but the problem isn't that bluez-plugins is missing - installing bluez-plugins effectively downgrades (part of?) bluez.

**Comment by Sunspark-007** [comment]
> This is not to say there's not been a regression, but the problem isn't that bluez-plugins is missing - installing bluez-plugins effectively downgrades (part of?) bluez.

I am not a Linux bluetooth expert at all, but my basic understanding of this is that the two are different things.

Valve needs to look into this simply because the issue affects more controllers than just this one.

**Comment by fledermaus** [comment]
https://archlinux.org/packages/extra/x86_64/bluez-utils/

```
Description: 	Development and debugging utilities for the bluetooth protocol stack
Upstream URL: 	http://www.bluez.org/
License(s): 	GPL-2.0-only
Provides: 	bluez-plugins
Replaces: 	bluez-plugins
```

**Comment by RyuzakiKK** [comment]
Thanks for reporting this issue. Yes, the Dualshock 3 is not working on SteamOS 3.6.20 because it is missing `bluez-plugins`.

As mentioned [above](https://github.com/ValveSoftware/SteamOS/issues/1710#issuecomment-2617840134), the short term fix is to manually install it. If you use `sudo pacman -Sy bluez-plugins` there should be no need to change the signature level in `pacman.conf`.

> bluez-plugins has been replaced (upstream, in bluez) by bluez-utils.

This is true for Bluez 5.73+. However in SteamOS 3.6 we still ship Bluez 5.66, where `bluez-plugins` is still a separate component.

**Comment by Heavyweightgd6** [comment]
Can someone please make a video? I'm very new to Linux and I don't understand any of this command line stuff. PS3 controller works fine a few months ago, wirelessly. Now it only works wired.

**Comment by justusiv** [comment]
> Can someone please make a video? I'm very new to Linux and I don't understand any of this command line stuff. PS3 controller works fine a few months ago, wirelessly. Now it only works wired.

I haven't tried it myself but SteamOS 3.6.23 Beta: Beak Visible has this in its notes. 
"Fixed pairing DualShock 3 controllers"

**Comment by Managor** [comment]
Doesn't work. The 3.7.0 preview even mentions this 
> DualShock 3 controllers are currently not able to be paired or use

**Comment by Sunspark-007** [comment]
People are reporting that the pairing works now with 3.6.24.

Thanks Valve for fixing this!

**Comment by Managor** [comment]
Can confirm. DS3 pairs on 3.6.24. For some reason this is not fixed on Main.
Next step is to fix Home + Y chord not shutting down the controller. https://github.com/ValveSoftware/steam-for-linux/issues/8066

**Comment by Managor** [comment]
Minor need for improvement: Remember devices that have been paired before.
Currently to use a DS3 wirelessly, you need to first use it wired and then pair it. Every time. If I shut down the Deck, I need to do this process again to use the controller.

**Comment by RyuzakiKK** [comment]
> Minor need for improvement: Remember devices that have been paired before.
> Currently to use a DS3 wirelessly, you need to first use it wired and then pair it. Every time. If I shut down the Deck, I need to do this process again to use the controller.

As a short term workaround you can go to desktop mode, plug in the USB cable and press "Authorize and Trust" in the bottom right notification.

After that, you should be able to connect the DS3 even after a reboot.

**Comment by trisk** [comment]
My previously paired DualShock 3 controllers stopped connecting after updating to SteamOS 3.7.5 Beta. They still appeared appearing paired in the Bluetooth settings and couldn't be removed. I had to manually remove them with `bluetoothctl` and then plug them in in desktop mode to select "Authorize and Trust" at the prompt, which paired them correctly.

**Comment by sweetol** [comment]
> > Minor need for improvement: Remember devices that have been paired before. Currently to use a DS3 wirelessly, you need to first use it wired and then pair it. Every time. If I shut down the Deck, I need to do this process again to use the controller.
> 
> +1
> 
> not really minor for me. becouse you cant wake up the deck.
> 
> i steel need to conntect with cable and repair the ps3 controller every time i need it in wireless. previously it wasnt needed.
> 
> morover, the repairing process sometimes doesn't work at first time, i need to try a few times before it works.

update:

now pairing is lost only when docked. only when you need it...and cant wake up my lcd

**Comment by Managor** [comment]
Pairs perfectly on Steamos 3.9. Probably works just as fine on Stable release. This can be closed.

**Comment by Schadows** [comment]
Doesn't work on Steam OS 3.8.11 on Steam Deck OLED.

I previously had my two dualshock 3 controllers paired with the Steam Deck. That was maybe 2 years ago, done thanks to installing bluez-plugins at the time.

But today:
1. Natively, it doesn't work (unable to pair the Dualshock 3 connected in USB).

2. /etc/bluetooth/input.conf was already existing, so I uncommented the options suggested so far:
- UserspaceHID=false
- ClassicBondedOnly=false
After a reboot, didn't make it work either.

3. I installed blue-plugins which was nowhere to be found (bluez and bluez-utils where already there in version 5.83-1.2), but the latest version is only 5.73-9 (probably because it was replaced by bluez-utils like someone said earlier).
After a reboot, didn't make it work either.

The only thing that I find strange is: when I paired my dualshock 3 controllers back then, and I gave them custom name at the time (like PS3 (***) to differenciate between them).
But now, despite having removed the PS3 controllers with bluetoothctl remove, and not seeing those controllers in the trusted devices list of the bluetooth panel, everytime I plug the controller through USB, the custom name I gave them at the time pops up in a notification (telling me it is connected ... and clicking on the notification does nothing).

I wonder if my controller is still know somewhere, but I haven't been able to find where.
