### ISSUE TITLE
Dock issues, battery issues, sound issues since 'go country'

### ISSUE THREAD

**Issue by AlexAssassin94** [ValveSoftware/SteamOS#1982]
Your system information

* Steam client version: 3.7.8
* SteamOS version: 20250522.2
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

Since the 'go country' update and the following version my deck has endless issues. These are all after a full factory reset.

Battery percentage no longer works - if you set a limit, it shows that limit number forever and shows the 'charging' icon even when unplugged and not charging. You have to restart the deck to see the actual battery percentage. 

Desktop mode now adds a desktop and home menu shortcut for every game installed, without me changing any settings. 

Official dock simply doesn't work anymore - either refuses to display anything, or has to be forcibly restarted, plugged and unplugged several times before working - previously worked no issue. 

Audio crackling, in games it wasn't present for before - both when docked and via bluetooth headphones.

Auto-sleep no longer happens, either docked or undocked. No matter what the screen off/sleep timers are set to, the deck will simply stay on forever (when docked) or until it runs out of battery.

**Comment by manuelafm** [comment]
Thanks for the report.  Some of these issues are know and either fixed or on its way, on more recent versions with 3.7.9, I recommend to try the beta version or the OS or wait for a few days when it's released and stable and re-test.

Also, in general it's more useful to report issues separately because of the way that they are worked on and fixed separately, otherwise the reported issue quickly become unmanageable.

Some comments:

> Battery percentage no longer works - if you set a limit, it shows that limit number forever and shows the 'charging' icon even when unplugged and not charging. You have to restart the deck to see the actual battery percentage.

There have been some improvements to this in `3.7.9`, not sure if completely fixed.

It would be useful if you can open the menu of the `(...)` physical button, then the `Performance ⚡`  tab, and see if the percentages/status battery match those of the top-right icon in the panel or not.


> Desktop mode now adds a desktop and home menu shortcut for every game installed, without me changing any settings.

This is known and I think that fixed in `3.7.9`.


> Audio crackling, in games it wasn't present for before - both when docked and via bluetooth headphones.

This is known, at least with some games, and the fix is work in progress.


> Official dock simply doesn't work anymore - either refuses to display anything, or has to be forcibly restarted, plugged and unplugged several times before working - previously worked no issue.

Maybe this is an issue with some screens, but I think that in general it works.  It would be useful if you shared the external screen model, resolution, etc, to see if we can find a pattern.

> Auto-sleep no longer happens, either docked or undocked. No matter what the screen off/sleep timers are set to, the deck will simply stay on forever (when docked) or until it runs out of battery.

I will try this.  Is your model an LCD or an OLED one?

**Comment by edfloreshz** [comment]
I just updated to 3.7.9 and I can confirm that it is not fixed.

**Comment by manuelafm** [comment]
> I just updated to `3.7.9` and I can confirm that the audio crackling issue is not fixed.

Thanks.  There's a fix queued for this for the next beta/stable in 3.7.

**Comment by manuelafm** [comment]
@AlexAssassin94 About battery charging that you reported, have there been any changes?

**Comment by AlexAssassin94** [comment]
I should say - model is an LCD, docking with the official dock to a Dell monitor. I have to unplug and replug each time the deck restarts now or there's issues with resolution/flickering.
