### ISSUE TITLE
Latest Controller firmware from Lenovo breaks Steam/ QAM buttons in steam OS

### ISSUE THREAD

**Issue by superczar** [ValveSoftware/SteamOS#2050]
#### Your system information

Your system information

Steam client version: [1752195011](tel:1752195011)
SteamOS version: 3.7.14 (build 20250701.1)
Opted into Steam client beta?: Yes
Opted into SteamOS beta?: Yes
Have you checked for updates in Settings > System?: Yes
Please describe your issue in as much detail as possible:

I have a Legion Go Z1E 
Steam OS was perfectly functional till today .
However the latest controller firmware updatE (0260618A) has broken the Steam / Quick Action buttons functionality altogether.

Steps for reproducing this issue:

1. Boot into windows
2. Launch Legion space - the app will auto update and also apply the latest FW on the controllers
3.  Reboot into Steam OS
4. Test the Steam/ QAM button. - they will likely be non functional

**Comment by pastaq** [comment]
Did you toggle into FPS mode?

**Comment by matte-schwartz** [comment]
opened https://github.com/ShadowBlip/InputPlumber/pull/399 to fix it

**Comment by pastaq** [comment]
Fix has been merged. As soon as SteamOS is updated to the latest InputPlumber it will be live. Adventurous folks can manually update after disabling read only mode.

**Comment by superczar** [comment]
Can confirm that a manual update of inputplumber fixes this!
Thanks for the super quick turnaround :)

**Comment by Andalitez** [comment]
> > > This doesn’t work.
> > 
> > 
> > Which step doesnt work for you? I wrote this 5 minutes after I successfully did it myself.
> 
> sudo cp inputplumber/usr/bin/inputplumber /usr/bin/inputplumber --> "text file busy"
> 
> After killing the inputplumber process, the “text file busy” error was gone, but the overlay buttons still don’t work.

Try the following in konsole.

sudo systemctl stop inputplumber
cd inputplumber
sudo cp -r usr/* /usr/

inputplumber --version 
(You should now see inputplumber 0.60.5.)

sudo systemctl enable inputplumber
sudo systemctl start inputplumber

sudo steamos-readonly enable


If inputplumber was launched manually or is running in the background, you can find and stop it with:

ps aux | grep inputplumber

Then kill the process using its PID:
sudo kill <PID>

Then follow the steps above from cd inputplumber

**Comment by adam-jachymek** [comment]
> > > > This doesn’t work.
> > > 
> > > 
> > > Which step doesnt work for you? I wrote this 5 minutes after I successfully did it myself.
> > 
> > 
> > sudo cp inputplumber/usr/bin/inputplumber /usr/bin/inputplumber --> "text file busy"
> > After killing the inputplumber process, the “text file busy” error was gone, but the overlay buttons still don’t work.
> 
> Try the following in konsole.
> 
> sudo systemctl stop inputplumber cd inputplumber sudo cp -r usr/* /usr/
> 
> inputplumber --version (You should now see inputplumber 0.60.5.)
> 
> sudo systemctl enable inputplumber sudo systemctl start inputplumber
> 
> sudo steamos-readonly enable
> 
> If inputplumber was launched manually or is running in the background, you can find and stop it with:
> 
> ps aux | grep inputplumber
> 
> Then kill the process using its PID: sudo kill
> 
> Then follow the steps above from cd inputplumber

It works, thanks a lot!

**Comment by amilcarrobles** [comment]
> > Replying to [#2050 (comment)](https://github.com/ValveSoftware/SteamOS/issues/2050#issuecomment-3089908503)
> 
> Thanks to you, it's working well. Thank you. Can I ask one more question? An additional controller named 'xbox elite controller' is registered, causing double input. Is there a way to delete or disable this controller?

Right, I'm having the same issue. You can reproduce this if you try to open quick access menu and set any slider (like, for example, the brightness adjustment) , you will not be able to set it with the gamepad.

**Comment by pastaq** [comment]
> > Replying to [#2050 (comment)](https://github.com/ValveSoftware/SteamOS/issues/2050#issuecomment-3089908503)
> 
> Thanks to you, it's working well. Thank you. Can I ask one more question? An additional controller named 'xbox elite controller' is registered, causing double input. Is there a way to delete or disable this controller?

I'll look into this, thanks for reporting.

**Comment by RunForest66** [comment]
> > Replying to [#2050 (comment)](https://github.com/ValveSoftware/SteamOS/issues/2050#issuecomment-3089908503)
> 
> Thanks to you, it's working well. Thank you. Can I ask one more question? An additional controller named 'xbox elite controller' is registered, causing double input. Is there a way to delete or disable this controller?

I had the same issue, fixed it by uninstall deckey plumber or set controller slider to steam deck in deckey plumber plugin.

**Comment by saeroyen** [comment]
> > > Replying to [#2050 (comment)](https://github.com/ValveSoftware/SteamOS/issues/2050#issuecomment-3089908503)
> > 
> > 
> > Thanks to you, it's working well. Thank you. Can I ask one more question? An additional controller named 'xbox elite controller' is registered, causing double input. Is there a way to delete or disable this controller?
> 
> I had the same issue, fixed it by uninstall deckey plumber or set controller slider to steam deck in deckey plumber plugin.

Thank you bro this worked for me. I installed the decky plumber then set the slider to steam deck.

**Comment by pastaq** [comment]
> > > Replying to [#2050 (comment)](https://github.com/ValveSoftware/SteamOS/issues/2050#issuecomment-3089908503)
> > 
> > 
> > Thanks to you, it's working well. Thank you. Can I ask one more question? An additional controller named 'xbox elite controller' is registered, causing double input. Is there a way to delete or disable this controller?
> 
> Right, I'm having the same issue. You can reproduce this if you try to open quick access menu and set any slider (like, for example, the brightness adjustment) , you will not be able to set it with the gamepad.

Fixed in v0.60.6

**Comment by SommerTranPham** [comment]
> > > > Replying to [#2050 (comment)](https://github.com/ValveSoftware/SteamOS/issues/2050#issuecomment-3089908503)
> > > 
> > > 
> > > Thanks to you, it's working well. Thank you. Can I ask one more question? An additional controller named 'xbox elite controller' is registered, causing double input. Is there a way to delete or disable this controller?
> > 
> > 
> > Right, I'm having the same issue. You can reproduce this if you try to open quick access menu and set any slider (like, for example, the brightness adjustment) , you will not be able to set it with the gamepad.
> 
> Fixed in v0.60.6

Many thanks for your quick support. 

I'm currently run 0.60.5, could you please let me know which command to update to latest version (0.60.7)? I'm sorry but I'm newbie in this area. Really appreciate it.

**Comment by Andalitez** [comment]
Same way you updated to 60.5?
Just change the version number...

Go to desktop mode, Konsole commands -

sudo steamos-readonly 

wget https://github.com/ShadowBlip/InputPlumber/releases/download/v0.60.7/inputplumber-x86_64.tar.gz

tar -xvzf inputplumber-x86_64.tar.gz

sudo systemctl stop inputplumber
cd inputplumber
sudo cp -r usr/* /usr/

inputplumber --version
(You should now see inputplumber 0.60.7.)

sudo systemctl start inputplumber

sudo steamos-readonly enable

**Comment by SommerTranPham** [comment]
> Same way you updated to 60.5? Just change the version number...
> 
> Go to desktop mode, Konsole commands -
> 
> sudo steamos-readonly
> 
> wget https://github.com/ShadowBlip/InputPlumber/releases/download/v0.60.7/inputplumber-x86_64.tar.gz
> 
> tar -xvzf inputplumber-x86_64.tar.gz
> 
> sudo systemctl stop inputplumber cd inputplumber sudo cp -r usr/* /usr/
> 
> inputplumber --version (You should now see inputplumber 0.60.7.)
> 
> sudo systemctl start inputplumber
> 
> sudo steamos-readonly enable

Many thanks for your quick reply. I've performed exactly your instruction but still see version 0.60.5 when executed inputplumber --version .  Perhaps, I've missed some steps? 

P/s: I'm running 0.60.5 well and the Legion R+L works now. But the B button seems not running properly at the "Home screen" in Game Mode. That's why I'd like to move to 0.60.7 to remove the "Elite" controller.

**Comment by Andalitez** [comment]
> Many thanks for your quick reply. I've performed exactly your instruction but still see version 0.60.5 when executed inputplumber --version . Perhaps, I've missed some steps?
> 
> P/s: I'm running 0.60.5 well and the Legion R+L works now. But the B button seems not running properly at the "Home screen" in Game Mode. That's why I'd like to move to 0.60.7 to remove the "Elite" controller.

Oh I think i know why its not changing for you.
You need to remove the older versions you downloaded previously (using the wget command) so something like this

find ~ -type f -name "inputplumber-x86_64.tar.gz*" -exec rm {} \;

Then follow the exact same steps I posted above

**Comment by pastaq** [comment]
@superczar that is terrible advice. 

From @SommerTranPham post above yours...
```
wget https://github.com/ShadowBlip/InputPlumber/releases/download/v0.60.7/inputplumber-x86_64.tar.gz
sudo systemctl stop inputplumber
tar -xvzf inputplumber-x86_64.tar.gz
cd inputplumber
sudo cp -r usr/* /usr/
sudo systemctl start inputplumber
sudo steamos-readonly enable
```
This effectively does the same thing without the headache or security issues.

**Comment by matte-schwartz** [comment]
a fix for this is now on the SteamOS Main channel, should make it to a Beta/Preview image soon.
