### ISSUE TITLE
Beta Update 1438115271 breaks wireless xbox 360 controllers.

### ISSUE THREAD

**Issue by Nocturnal42** [ValveSoftware/SteamOS#349]
Since the update my wireless xbox 360 controller (connected via a usb Xbox 360 Wireless Gaming Receiver) does not function correctly. The direction pad does not function, the left stick and main buttons work (have not tested others), but I am unable to reconfigure the keymap.

In the Settings -> Controller menu, multiple detected devices are listed, but cannot be selected. This is what it looks like

![img_6228](https://cloud.githubusercontent.com/assets/4250515/8962066/002652d6-365c-11e5-96b5-d0cc80b586f9.JPG)

This is what it looked like under the previous version.

![img_6226](https://cloud.githubusercontent.com/assets/4250515/8962133/461969b8-365c-11e5-97c9-b668a5998c75.JPG)

**Comment by ProfessorKaos64** [comment]
Can you report if this is independent of release (Alchemist/Brewmaster beta/non-beta)? I'll check this behavior tonight on my Alchemist (main box) install tonight as I have wireless Xbox 360 controllers from Microsoft as well.

**Comment by Nocturnal42** [comment]
With Brewmaster I get the issue with both beta/non-beta. The settings=>controller screen looks the same for Alchemist/Brewmaster beta (show in first post), but looks like so in Brewmaster non-beta

![img_6230](https://cloud.githubusercontent.com/assets/4250515/8975954/fcea960a-36c8-11e5-8eca-1c3eb8bcfa97.JPG)

**Comment by Nocturnal42** [comment]
My controllers are not 3rd party, otherwise I would have mention that. The controllers don't have a usb id, since they are not connected via usb. The usb id of the receiver is 045e:0291, and under brewmaster the Xorg log lists the detected input devices as "Xbox 360 Wireless Receiver" as it enumerates for the four possible controllers (twice for each controller, one event handler and one joystick for each). Which is related to why the beta screen lists 8 input devices.

**Comment by MattDevo** [comment]
my wireless 360 controllers are recognized as XInput compatible controllers as well under Brewmaster, but I'm using an updated xpad driver ( https://github.com/paroj/xpad/tree/master ) so only connected controllers are shown, not all 4 possible

**Comment by ProfessorKaos64** [comment]
I can confirm I have this under Alchemist as well. So this is not a SteamOS issue, but a client issue I believe. A dev / community manager can confirm here. This likely is then something that needs reported in the Steam beta client group on steamcommunity.com. My controller (MS, X360, wireless) does work fine, but I do see the multiple entries as reported.

**Comment by MattDevo** [comment]
mine work fine as well, but obviously can no longer be configured through the client

**Comment by Nocturnal42** [comment]
So I did some testing with all my controllers and both wireless receivers, it seems that paired to the first wireless receiver I have the d-pad issues, while paired to the second receiver I do not. 

Both have the same usb id and both enumerate the same. Both work perfectly in alchemist non-beta.

**Comment by Vash63** [comment]
I use a DS4 but that menu also does the same thing on my end, on Brewmaster.

**Comment by ProfessorKaos64** [comment]
This should be fixed at least in the client Beta @Nocturnal42 , can you retest and/or close the ticket if so?

**Comment by MrSchism** [comment]
I'm using the wireless controller, but connected via a USB adapter (Nyko).  lsusb` identifies it, but it's not usable in client.  I'm going to check it out now; I'm on Brewmaster with a beta Steam Client.

**Comment by MrSchism** [comment]
In my case, there's no resolution.  In the actual wireless mode, there may be a resolution, though.

**Comment by Nocturnal42** [comment]
Not fixed. In Alchemist beta, the controller is listed as xinput device and highlighted and "support" is selected, I get a screen showing a steam controller and instructing to pull the left trigger (I think that's what it was), from which I can do nothing except exit. Brewmaster beta is the same, except it shows 4 xinput devices.

Still the weird D-pad issue as well.

**Comment by ProfessorKaos64** [comment]
@Nocturnal42 , Alchemist is no longer supported. For uprade help see the wiki here.
