### ISSUE TITLE
PS4/DS4 Controller spams 'X' (cross) and sometimes a navigational direction after connecting

### ISSUE THREAD

**Issue by Enigma0** [ValveSoftware/SteamOS#513]
#### Your system information

* Steam client version: latest public brewmaster
* SteamOS version: latest public brewmaster
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] No (probably - not sure where to find that information)
* Have you checked for updates in Settings > System?: [Yes/No] Yes - should be running latest

#### Please describe your issue in as much detail as possible:

Happens with pretty high regularity. Happened last three times I booted SteamOS and turned on controller.

- Sometimes after turning on the PS4 controller high frequency 'a'/'x' (cross) pushes start occurring that cannot be stopped. Results in a whole bunch of mayhem and usually a game launch.

In order to 'fix' it, I need to hold the PS button until the controller turns off which always results in the glitch automatically launching into Desktop.

#### Steps for reproducing this issue:

1. Plug in USB Bluetooth 4.0+ dongle
2. Pair PS4 controller
3. Navigate around/hit a few buttons
4. Turn off controller & turn on controller and repeat step 3

- May need to turn off controller after paring and then turn it back on
- May need to restart SteamOS and then turn on after pairing
- Once it's been powered on and the glitch hasn't occurred (or after playing in a game for a while) it doesn't seem to occur any longer until the next time it's connected.

**Comment by SoulEst** [comment]
Unfortunately, this is the issue with having DualShock 4 controllers connected via Bluetooth. I have yet to find a solution to it so I have them connected via USB for now.

**Comment by Enigma0** [comment]
Seems like an issue that could be easily resolved in the Bluetooth stack. If the hardware is not defective, and is in fact not actually sending out button spams, then it is a mis-identification of the incoming Bluetooth data.

Mayflash will be making a PS4 controller dongle like their PS3 controller dongle in several months.

**Comment by SoulEst** [comment]
The issue is twofold as you not only have the bluetooth stack, but the kernel driver as well. I understand that the polling issue in the kernel driver has been fixed some time ago. Not sure where the issue lies now.

**Comment by Enigma0** [comment]
I'd be willing to look at code as well but have 0 experience with this sort of environment. Can't make heads or tails of where any relevant source code may be... I mean it looks like none of it is even hosted on github for starters.

**Comment by SoulEst** [comment]
Have a look here: https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/log/?id=refs/tags/v4.5.5 and search for dualshock. The relevant file is at drivers/hid/hid-sony.c. I've compared the driver in the stable kernel (4.5.x) with the driver in the SteamOS kernel (4.1.x) and have found a large difference between the two (over 400 lines of code added for 4.5.5). I have yet to analyze them in depth however. I haven't compared the bluetooth code for the two kernels either.

Anyway, here are the hid-sony.c file for Linux 4.1 (SteamOS), Linux 4.5.5 (Stable), and a diff that shows the two files side by side.
[hid-sony-diff.zip](https://github.com/ValveSoftware/SteamOS/files/292411/hid-sony-diff.zip)

**Comment by Enigma0** [comment]
So I did do some testing in Ubuntu GNOME 15.10 (and maybe 16.04 can't remember) and noticed the same issues with the bluetooth controller so I'd wager the problems are still there in 4.5.x.

**Comment by Tele42** [comment]
This issue needs to be fixed upstream before a patch can be proposed to improve the situation on SteamOS.

**Comment by ELLIOTTCABLE** [comment]
As a data-point, this exact same issue happens to me with a DualShock 4 in standard Big Picture Mode *on OS X*. I do not believe this issue to be localized to the SteamOS bluetooth stack, or to the tenfoot display-mode.

**Comment by Enigma0** [comment]
Well IIRC OS X also uses Linux kernels (probably modified) so basically that just helps confirm it's an issue across Linux kernels which I think was already known since the same issue happens in other Debian distros as it is.

Hence Tele42's comment about this issue needing to be fixed upstream. Basically my report here is kind of pointless >.>

**Comment by ELLIOTTCABLE** [comment]
n…no, OS X does not use any part of the Linux kernel, much less the
Bluetooth stack. (Darwin microkernel, and eeeeentirely custom / unrelated
network stack)

That's why I brought it up: I don't see the repeated-cross /
repeated-directional-left-and-up behaviour outside of Steam Big Picture
mode; so it follows that it's not reproduced in the system-level Bluetooth
drivers; it's almost certainly specific to Steam, no?

**Comment by Enigma0** [comment]
Interesting... Didn't consider that it wasn't an issue after getting into a game but I don't think I've seen this issue in game either. Just in BPM.

So ya my bad. I think your right about that.

**Comment by yaccin** [comment]
I have the same issue as well unfortunately.
