### ISSUE TITLE
[ SteamOS 2.87 ] Back in Fatal Error Loop again. 

### ISSUE THREAD

**Issue by ekianjo** [ValveSoftware/SteamOS#546]
#### Your system information

* Steam client version: latest beta
* SteamOS version: 2.87
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Just upgraded a few days ago from 2.70 to 2.87. Apart from one crash post update, the system was booting fine and everything was normal and once I was confident I made a recovery image with "capture partition" in the boot GRUB menu. I never stopped the system in any abnormal way, yet today once again I got into the fatal error loop, where at boot you see a blinking mouse cursos and then lines across the screen flashing back and forth until the system says it has a fatal error and tries to fix it. After the operation is done, it reboots and the very same thing occurs. I.e. the fatal error recovery completely fails.

I then tried to recover the system partition from GRUB, yet the very same thing occured again. The system is now completely borked (again! I had the same issue with 2.70 before) and I basically have to reinstall it from scratch. 

Can you seriously consider this issue and either improve the fatal error recovery process or the partition restoration process? Having a non-stable system like that is really a big problem.

#### Steps for reproducing this issue:

See above.

**Comment by nimbius** [comment]
same issue here.  steamos-session execution bombs out with invalid ELF class for an i386 library called libmodeswitch_inhibitor.  the steamos recovery script does not solve this issue.

**Comment by ProfessorKaos64** [comment]
That is not the problem. The flags for libmodeswitch have been there forever. I believe both 64 and 32 bit libs are there and you're just seeing the preload rejection for the one you don't have. You'd have to check out the Steam bootstrap and steam.sh scripts etc. to see this.

**Comment by littlegamer87** [comment]
See http://steamcommunity.com/groups/steamuniverse/discussions/1/360670708783302041/
This is probably the same issue, corrupted client caused by the halted client update

A possible solution for autorecovery has also been submitted by ProfessorKaos64
https://github.com/ValveSoftware/SteamOS/issues/542

A possible workaround could be:
- Boot from ISO and get a recovery shell
- Disable lightdm autologin
- Boot normally and login as desktop
- Launch X and recover the client somehow as user steam

You can use sudo -u steam steam to run something as the steam user, maybe steam --reset will work

**Comment by ProfessorKaos64** [comment]
I added a little bit of a blurb to the cannot start SteamOS piece noting this. I had something already, but clarified a bit.

**Comment by ekianjo** [comment]
the steam --reset command did not fix anything, still getting in the fatal error loop in the end.

HOWEVER, I found what is causing the issue thanks to a prior post. The tenfoot folder is missing in /home/steam/.local/share/Steam and that is now showing that the client is attempting an update when I boot up... still half way there though, as the update fails and it goes back into "failed to apply update, reverting.." loop now. but something this is an improvement.

**Comment by VaysseB** [comment]
Did the latest update actually broke Steamos for anyone ? Even the freshly new installation ?
Or does it mean it corrupts only previous installations, and the only solution is to fully remove and install it again ?

**Comment by ekianjo** [comment]
Ok I fixed my install by doing the following: 

1. copy the tenfoot folder from my other computer with Steam installed to the SteamOS machine in /home/steam/.local/share/Steam
2. you need to modify the permissions by executing this commend in the above folder: sudo chown -R steam:steam tenfoot/
3. confirm that steam is the new owner of the folder by doing: ls -l tenfoot
4. reboot (shutdown -r now)

The process will then fix the install by itself and bring you back to Steam as expected. 
Note that is a workaround and I am keeping this issue open until Valve fixes this.

**Comment by nimbius** [comment]
fwiw I decided to reimage, partly because my steam experience prevents catastrophic failures like this from really impacting my gaming experience. i just resync from valve and my games are good-as-new. This problem likely would not have been debilitating had I simply taken a recovery snapshot during first install, however the snapshot process isnt intuitive. 

August 6 2016 11:05 PM, "ekianjo"  wrote:
	Ok I fixed my install by doing the following:
	* copy the tenfoot folder from my other computer with Steam installed to the SteamOS machine in /home/steam/.local/share/Steam
	* you need to modify the permissions by executing this commend in the above folder: sudo chown -R steam:steam tenfoot/
	* confirm that steam is the new owner of the folder by doing: ls -l tenfoot
	* reboot (shutdown -r now)
	The process will then fix the install by itself and bring you back to Steam as expected.
Note that is a workaround and I am keeping this issue open until Valve fixes this.

**Comment by ekianjo** [comment]
the recovery snapshot does not work in this case, @nimbius, as I mentioned already in my first post. Even when recovering the fatal error loop comes back.

**Comment by ProfessorKaos64** [comment]
I wonder if I could figure out a solution to reset the client in the auto recovery script and test it. This is tough, since my test machine is a fresh install, and has not gotten this issue. I would need a guinea pig :) If Valve isn't going to publicly address this yet, I should just figure it out myself. Check for a few key items (like what ekianjo described), and if they are missing, reinstall/correct them.

**Comment by Enigma0** [comment]
This just happened to me. Thankfully I enabled ssh server before so I get some access time between the recoveries n forced reboots. Recovery fails to fix the problem.

I'll give that a try.

**Comment by littlegamer87** [comment]
@ProfessorKaos64 Maybe removing the tenfoot folder, as described by @ekianjo, will introduce this issue. Worth a shot.

@Enigma0 before attempting to mess around with drivers, I would advise to check if the driver has been loaded in the first place. Most feedback thus far says this is the client crashing, not the driver. The issue where GLX loaded the wrong driver (which also gives black screens) should be resolved.

**Comment by ProfessorKaos64** [comment]
@littlegamer87 , would you know that i received the flashing arrow cursor / black screen this morning :) I backed up the old script, added mine. However, like @ekianjo said, this does not replace/install the tenfoot folder in `/home/steam/.local/share/Steam`. I need to figure out how that gets replaced, and add that to my script. Now I can functionally test my new repair process. I have to go to work, but should be an interesting thing to try tonight.

**Comment by ProfessorKaos64** [comment]
Usually packages/ is populated when running steam on the cli, but I don't know if it's possible to kick this off without X. Maybe divert X to allow it to run. See [this issue](https://github.com/ValveSoftware/steam-for-linux/issues/3501) for some idea.

**Comment by ProfessorKaos64** [comment]
Nice! This worked over SSH:

````
sudo -su - steam -c 'DISPLAY=:0 /usr/bin/steam
```

If this works, I'll add this to my version of the auto repair script. If Valve denies to accept my version as an improvement (I don't know even where to suggest it as a change), I will post instructions on the SteamOS-Tools wiki and here what to run manually via recovery mode or SSH.

**Comment by ProfessorKaos64** [comment]
Going to push stdout and street to a log in /to with my. Version so all a tions can be reviewed in real-time with `tail`, or later as needed.

**Comment by ProfessorKaos64** [comment]
You can run Steam via a "fake X server" or X11 forwarding. 

Example:

xvfb-run -a -e ~/log.txt steam

**Comment by ProfessorKaos64** [comment]
Confirmed the above works. Tested 3 times after removing various folders under `/home/steam/.local/share/Steam/`. You do* have net access (if wired), so this is possible to hook into the autorepair script, but you can't assume that. I do believe something like this is vital to the auto-repair process. Maybe a backup folder gets written on update of the Steam Client (last successful launch), and if folders fail integrity checks, restore the last backup to the above location.

**Comment by ekianjo** [comment]
Thanks @ProfessorKaos64 for finding this out! This is great progress. Agree with you that we need to have an online solution for this kind of issue. One thing I was wondering, why is that issue never happening on Linux distro + Steam Client vs SteamOS (i.e. the client getting corrupted and missing specific folders?) ? Is there something specific to SteamOS that makes the updating process less reliable?

**Comment by ekianjo** [comment]
@ProfessorKaos64 Btw to contribute to SteamOS is there any other repository apart from http://repo.steampowered.com/steamos/ ?

**Comment by ProfessorKaos64** [comment]
Because the Steam client update occurs normally when you launch it. Steam checks for client updates after your are in BPM and then offers to update after vs. the desktop standard client updating and echoing before you hit the desktop GUI. 

On August 16, 2016 9:02:09 PM EDT, ekianjo <notifications@github.com> wrote:
>Thanks @ProfessorKaos64 for finding this out! This is great progress.
>Agree with you that we need to have an online solution for this kind of
>issue. One thing I was wondering, why is that issue never happening on
>Linux distro + Steam Client vs SteamOS (i.e. the client getting
>corrupted and missing specific folders?) ? Is there something specific
>to SteamOS that makes the updating process less reliable?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ValveSoftware/SteamOS/issues/546#issuecomment-240285149

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ekianjo** [comment]
I see. But if that's the case, why not run an integrity check of the client before going in BPM ?

**Comment by johnv-valve** [comment]
I believe this is fixed in 2.88. The steam update will work even if the tenfoot folder is missing.

**Comment by ekianjo** [comment]
@johnv-valve thanks - when will 2.88 become the new stable version though ?

**Comment by ProfessorKaos64** [comment]
@ekianjo , you have to be patient. Sometimes it's a few weeks, could be more. Seldom it's less than 3 weeks, if I recall.

**Comment by ekianjo** [comment]
Got the issue again. The time the tenfoot golder is not missing. And @ProfessorKaos64 command line tip returned that xvfb is not in /usr/bin/ so it does not fix the issue. What to do?

**Comment by ekianjo** [comment]
Lidsdl2 libgtk libavcodec libavformat libavresample libavutil libswscale 32 bit libraries are missing and steam may not run. This is the message I am getting.

**Comment by ProfessorKaos64** [comment]
...you need to install the package "xvfb", which is noted in the wiki if you try that step. I'll write the actual installation command in so it's clear.

**Comment by ekianjo** [comment]
I just did (before even getting your message) but it still does not seem to solve the issue. I am getting the message that the libraries are missing, and nothing else happens in the command line.

**Comment by ProfessorKaos64** [comment]
I'll run the command set in recovery mode to be sure.

**Comment by ekianjo** [comment]
Thanks. Seriously if I can't fix this one without reinstalling, I'm giving up on SteamOS :(

**Comment by ProfessorKaos64** [comment]
I'm your neighborhood unofficial unpaid support rep :)

On August 23, 2016 7:17:19 PM EDT, ekianjo <notifications@github.com> wrote:
>Thanks. Seriously if I can't fix this one without reinstalling, I'm
>giving up on SteamOS :(
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ValveSoftware/SteamOS/issues/546#issuecomment-241910194

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ekianjo** [comment]
So @ProfessorKaos64 did you try it on your side ? Did not work for me in recovery mode (nothing happens, process seems to hang).

**Comment by ProfessorKaos64** [comment]
I was feeling a little under the weather. I'll make a point to try that tonight. The way I did it before was to SSH in while the screen was flickering/autorepairing and do it then. I'll test recovery mode.

**Comment by ekianjo** [comment]
thanks, let me know what happens on your side.

**Comment by ProfessorKaos64** [comment]
I amended thee wiki piece to note you will need a network connection. This should be fine if you are hard wired, if not, you will need to get an IP assigned. The commands that were already there worked fine for me after forcefully breaking my system by removing the tenfoot folder. I added a WLAN USB adapter to test wireless commands. It is best to just connect a wired cable

**Comment by Enigma0** [comment]
So I tried entering `sudo su - steam -c 'DISPLAY=:0 /usr/bin/steam` but it just drops me to a `>` prompt. How exactly do I fix my broken black screen system?

**Comment by ProfessorKaos64** [comment]
@Enigma0 you can't do that from the cli...that's why I included the xvfb tool instructions in the wiki.

**Comment by Enigma0** [comment]
@ProfessorKaos64 Is it in this wiki somewhere? (https://github.com/ValveSoftware/SteamOS/wiki/SteamOS-auto-repair-process) which wiki do I want to look at?

**Comment by ProfessorKaos64** [comment]
https://github.com/ValveSoftware/SteamOS/wiki/Troubleshooting#what-to-do-if-you-cannot-start-steamos

**Comment by Enigma0** [comment]
@ProfessorKaos64 Ah a link within a link. I think this command needs a `sudo` `su - steam -c '/usr/bin/xvfb-run -a -e /tmp/steam_update_log.txt /usr/bin/steam'`.

**Comment by ProfessorKaos64** [comment]
No, you are user "root" in recovery. The wiki makes a point to make the distinction. I'll recheck. 

On August 25, 2016 6:52:33 PM EDT, Enigma <notifications@github.com> wrote:
>@ProfessorKaos64 Ah a link within a link. I think this command needs a
>`sudo` `su - steam -c '/usr/bin/xvfb-run -a -e
>/tmp/steam_update_log.txt /usr/bin/steam'`.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ValveSoftware/SteamOS/issues/546#issuecomment-242570080

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ProfessorKaos64** [comment]
Try a steam --reset in there. Otherwise, apt-get install -f or find what packages correspond at packages.debian.org/package_name

**Comment by ekianjo** [comment]
@ProfessorKaos64 the steam --reset does nothing useful. In my case it actually erased the tenfoot folder! This is.... horrible.

**Comment by ekianjo** [comment]
@Enigma0 I have the same problem as you, with the same listed libraries as missing. Recovery did not help again. System is completely borked with apparently no way of fixing it (PK's commands do nothing for me).

**Comment by ProfessorKaos64** [comment]
All I can tell you is I tested them fine in recovery mode (provided I had a working network connection). If you are having this much trouble, I would suggest reinstalling. Maybe of note, is the breakdown only has ever happened to my .iso legacy BIOS install (my test machine).

**Comment by ekianjo** [comment]
@ProfessorKaos64 Thanks PK for all you have done here to help folks. I have decided to ditch SteamOS for good. It's just too broken for its own good. I wish everyone who keeps using it good luck, and I just hope I'm one of the unlucky few.

**Comment by Enigma0** [comment]
@ekianjo I had no luck getting it working again either and instead of reinstalling and dealing with no system sleep support, no screen mirroring, no ppa support, etc, I switched to a 16.04.1 Ubuntu GNOME based Steam Machine. Launches Steam BPM on boot, supports desktop based steam, supports multiple steam libraries, etc.

Not giving up on SteamOS but it needs like 6 months to a year+ more development, bug fixing and features...
